//! Diagnostics for filesystem watching and rebuild coordination failures.

use std::path::Path;

use super::fs::WatchError;
use tola_build::diagnostic::{Diagnostic, DiagnosticError, Severity};

pub(crate) fn with_diagnostics(error: anyhow::Error, root: &Path) -> anyhow::Error {
    if error
        .chain()
        .any(|cause| cause.is::<tola_build::cancellation::BuildCancelled>())
        || tola_build::diagnostic::attached(&error).is_some()
    {
        return error;
    }
    let diagnostic = error_diagnostic(&error, root, crate::codes::watch::RUNTIME);
    anyhow::Error::new(DiagnosticError::attach(error, vec![diagnostic]))
}

fn error_diagnostic(
    error: &anyhow::Error,
    root: &Path,
    fallback_code: tola_build::diagnostic::DiagnosticCode,
) -> Diagnostic {
    classify(error, root).unwrap_or_else(|| tola_build::diagnostic::fallback(fallback_code, error))
}

fn classify(error: &anyhow::Error, root: &Path) -> Option<Diagnostic> {
    let watch = error
        .chain()
        .find_map(|cause| cause.downcast_ref::<WatchError>())?;
    Some(match watch {
        WatchError::Create(_) => Diagnostic::new(
            crate::codes::watch::CREATE,
            Severity::Error,
            "Tola could not start watching files for changes",
        )
        .with_help("Raise your file-watch limit, then restart `tola dev`"),
        WatchError::Event(_) => Diagnostic::new(
            crate::codes::watch::EVENT,
            Severity::Error,
            "Tola stopped receiving filesystem changes",
        )
        .with_help("Restart `tola dev` with `-v` to see the failure"),
        WatchError::Stopped => Diagnostic::new(
            crate::codes::watch::STOPPED,
            Severity::Error,
            "Tola stopped watching files for changes",
        )
        .with_help("Restart `tola dev` to resume watching files"),
        WatchError::HookInputs(_) => Diagnostic::new(
            crate::codes::watch::HOOK_INPUTS,
            Severity::Error,
            "Tola could not watch the files generated by before-build hooks",
        )
        .with_help("Check the `[[build.hooks.before-build]]` commands in the site configuration"),
        WatchError::Attach { path, .. } => match watched_path(path, root) {
            Some(relative) => Diagnostic::at_path(
                crate::codes::watch::ATTACH,
                Severity::Error,
                relative,
                "Tola could not watch this path for changes",
            )
            .with_help("Restart `tola dev` to attach the file watch again"),
            None => Diagnostic::new(
                crate::codes::watch::ATTACH,
                Severity::Error,
                "Tola could not watch a configured path for changes",
            )
            .with_help("Check the `watch` paths declared in the site configuration"),
        },
    })
}

/// The site-relative spelling, or `None` for a path outside the site or the site root itself.
fn watched_path(path: &Path, root: &Path) -> Option<String> {
    let relative = path.strip_prefix(root).ok()?;
    if relative.as_os_str().is_empty() {
        return None;
    }
    Some(crate::terminal::display_path_within(path, root))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn backend_errors_keep_watch_codes() {
        let error = anyhow::Error::new(WatchError::Stopped);
        let error = with_diagnostics(error, Path::new("/site"));
        let diagnostics = tola_build::diagnostic::attached(&error).unwrap();
        assert_eq!(diagnostics[0].code, crate::codes::watch::STOPPED);
    }

    #[test]
    fn attached_paths_stay_site_relative() {
        let error = anyhow::Error::new(WatchError::Attach {
            path: Path::new("/site/content").to_path_buf(),
            source: notify::Error::generic("watch limit reached"),
        });
        let error = with_diagnostics(error, Path::new("/site"));
        let diagnostic = &tola_build::diagnostic::attached(&error).unwrap()[0];
        assert_eq!(diagnostic.code, crate::codes::watch::ATTACH);
        assert_eq!(diagnostic.location.as_ref().unwrap().path, "content");
        assert!(diagnostic.notes.is_empty());
        assert!(!format!("{error:#}").contains("/site/content"));
    }
}
