import assert from 'node:assert/strict'
import { mkdir, mkdtemp, readdir, readFile, rename, rm, writeFile } from 'node:fs/promises'
import { join } from 'node:path'
import { errorMessage, runProcess } from '../process.ts'
import { createArchive, verifyArchive } from './archives.ts'
import { type ArchiveDigests, checkChecksums, checksumContents } from './checksums.ts'
import { ordinaryDestination, ordinaryDirectory, regularFile } from './packaging-file.ts'
import { withoutBuildMetadata } from './semver.ts'
import { createLicenseArchive, licenseArchiveMembers } from './tar-archive.ts'
import { archiveName, hostTargetName, TARGET_NAMES, type TargetName, TARGETS } from './targets.ts'

/** The one archive a release carries the license material in. */
export function licenseArchiveName(version: string): string {
  return `tola-${withoutBuildMetadata(version)}-licenses.tar.gz`
}

/**
 * License material the release's one archive carries: member name → repository path.
 *
 * Every third-party work the binary embeds owes its licence text here: the fonts' notice, the two
 * pronunciation sources' licence and terms, and one snapshot per code theme. `THIRD-PARTY-LICENSES.txt`
 * is generated by `just licenses` and covers the Rust crates; the other files live in the repository.
 */
export const LICENSE_FILES: Readonly<Record<string, string>> = {
  'LICENSE': 'LICENSE',
  'LICENSE-1337-scheme': 'crates/tola-packages/licenses/LICENSE-1337-scheme',
  'LICENSE-APACHE-2.0': 'crates/tola-lsp/LICENSE',
  'LICENSE-CC-BY-SA-4.0': 'crates/tola-pronunciations/licenses/LICENSE-CC-BY-SA-4.0',
  'LICENSE-EDRDG.html': 'crates/tola-pronunciations/licenses/EDRDG-LICENCE.html',
  'LICENSE-UNICODE': 'crates/tola-pronunciations/licenses/LICENSE-UNICODE',
  'LICENSE-a11y-syntax-highlighting': 'crates/tola-packages/licenses/LICENSE-a11y-syntax-highlighting',
  'LICENSE-catppuccin-bat': 'crates/tola-packages/licenses/LICENSE-catppuccin-bat',
  'LICENSE-coldark-bat': 'crates/tola-packages/licenses/LICENSE-coldark-bat',
  'LICENSE-dracula-sublime': 'crates/tola-packages/licenses/LICENSE-dracula-sublime',
  'LICENSE-gruvbox-tmtheme': 'crates/tola-packages/licenses/LICENSE-gruvbox-tmtheme',
  'LICENSE-nord-plist': 'crates/tola-packages/licenses/LICENSE-nord-plist',
  'LICENSE-onehalf': 'crates/tola-packages/licenses/LICENSE-onehalf',
  'LICENSE-primer-github-textmate-theme':
    'crates/tola-packages/licenses/LICENSE-primer-github-textmate-theme',
  'LICENSE-solarized': 'crates/tola-packages/licenses/LICENSE-solarized',
  'LICENSE-sublime-monokai-extended': 'crates/tola-packages/licenses/LICENSE-sublime-monokai-extended',
  'LICENSE-sublime-snazzy': 'crates/tola-packages/licenses/LICENSE-sublime-snazzy',
  'LICENSE-tokyonight-nvim': 'crates/tola-packages/licenses/LICENSE-tokyonight-nvim',
  'LICENSE-twodark': 'crates/tola-packages/licenses/LICENSE-twodark',
  'LICENSE-zenburn': 'crates/tola-packages/licenses/LICENSE-zenburn',
  'NOTICE-TYPST-ASSETS': 'crates/tola-typst/NOTICE',
  'PROVENANCE-TOLA-LSP.md': 'crates/tola-lsp/licenses/README.md',
  'PROVENANCE-TOLA-PACKAGES.md': 'crates/tola-packages/licenses/README.md',
  'PROVENANCE-TOLA-PRONUNCIATIONS.md': 'crates/tola-pronunciations/licenses/README.md',
  'PROVENANCE-TOLA-TYPST.md': 'crates/tola-typst/licenses/README.md',
  'THIRD-PARTY-LICENSES.txt': 'THIRD-PARTY-LICENSES.txt',
}

export interface VerifyDirectoryOptions {
  readonly target?: TargetName
  readonly verifyChecksums?: boolean
  /** Targets whose archives the directory must contain exactly. Defaults to every target. */
  readonly targets?: readonly TargetName[]
}

export interface ReleaseBuildOptions {
  /** The workspace whose sources are built. */
  readonly root: string
  /** Directory receiving the finished archives. */
  readonly output: string
  /** Targets to build; defaults to the one target this host produces natively. */
  readonly targets?: readonly TargetName[]
}

export async function verifyDirectory(
  directory: string,
  version: string,
  options: VerifyDirectoryOptions = {},
  signal?: AbortSignal,
): Promise<ArchiveDigests> {
  signal?.throwIfAborted()
  await ordinaryDirectory(directory)
  const selected = options.target === undefined ? (options.targets ?? TARGET_NAMES) : [options.target]
  const expected = new Set<string>(selected.map((name) => archiveName(name, version)))
  const actual = new Set(await readdir(directory))
  const missing = [...expected].filter((name) => !actual.has(name)).sort()
  const licenses = licenseArchiveName(version)
  const missingLicenses = actual.has(licenses) ? [] : [licenses]
  const unexpected = [...actual]
    .filter((name) => name !== 'checksums.txt' && name !== licenses && !expected.has(name))
    .sort()
  assert(
    missing.length === 0 && missingLicenses.length === 0 && unexpected.length === 0,
    `release set mismatch: missing ${JSON.stringify(missing)}, missing license files ${
      JSON.stringify(missingLicenses)
    }, unexpected ${JSON.stringify(unexpected)}`,
  )
  if (actual.has('checksums.txt')) await regularFile(join(directory, 'checksums.txt'))
  if (actual.has(licenses)) {
    await regularFile(join(directory, licenses))
    const members = await licenseArchiveMembers(join(directory, licenses), signal)
    const absent = Object.keys(LICENSE_FILES).filter((name) => !members.includes(name)).sort()
    assert(absent.length === 0, `license archive lacks ${JSON.stringify(absent)}`)
  }
  const digests = new Map<string, string>()
  for (const name of selected) {
    const archive = archiveName(name, version)
    digests.set(archive, await verifyArchive(join(directory, archive), TARGETS[name], version, signal))
  }
  if (options.verifyChecksums !== false && actual.has('checksums.txt')) {
    await checkChecksums(join(directory, 'checksums.txt'), digests, signal)
  }
  signal?.throwIfAborted()
  return digests
}

/**
 * Build one release target with Cargo and package its binary.
 *
 * The release profile's fat LTO is requested here so the workspace default stays thin.
 */
export async function build(
  targetName: TargetName,
  version: string,
  options: ReleaseBuildOptions,
  signal?: AbortSignal,
): Promise<void> {
  signal?.throwIfAborted()
  console.log(`Building ${targetName}`)
  const result = await runProcess(
    'cargo',
    ['build', '--release', '--locked', '-p', 'tola', '--target', targetName],
    {
      env: {
        ...process.env,
        CARGO_PROFILE_RELEASE_LTO: 'fat',
        // A Linux archive is the static one: the vendored OpenSSL and the C runtime both link
        // statically. The musl target does this by default; naming it makes the requirement
        // unmistakable, and a dynamic input then fails the link instead of the archive check.
        ...(targetName.endsWith('-musl')
          ? { OPENSSL_STATIC: '1', RUSTFLAGS: '-C target-feature=+crt-static' }
          : {}),
      },
      stderr: 'inherit',
      ...(signal === undefined ? {} : { signal }),
    },
  )
  signal?.throwIfAborted()
  assert(!result.timedOut && result.exitCode === 0, `Cargo build failed (${result.exitCode})`)
  const source = join(options.root, 'target', targetName, 'release', TARGETS[targetName].binary)
  await packageBinary(source, options.output, targetName, version, signal)
}

export async function packageBinary(
  source: string,
  output: string,
  targetName: TargetName,
  version: string,
  signal?: AbortSignal,
): Promise<void> {
  signal?.throwIfAborted()
  const target = TARGETS[targetName]
  const archive = archiveName(targetName, version)
  await regularFile(source)
  signal?.throwIfAborted()
  await mkdir(output, { recursive: true })
  await ordinaryDirectory(output)
  const destination = join(output, archive)
  await ordinaryDestination(destination)
  signal?.throwIfAborted()
  const staging = await mkdtemp(join(output, `.${targetName}-`))
  try {
    const staged = join(staging, archive)
    await createArchive(source, staged, target, signal)
    await verifyArchive(staged, target, version, signal)
    await ordinaryDirectory(output)
    await ordinaryDestination(destination)
    signal?.throwIfAborted()
    await rename(staged, destination)
  } finally {
    await rm(staging, { recursive: true, force: true })
  }
  signal?.throwIfAborted()
  console.log(`Wrote ${destination}`)
}

export async function checksums(
  directory: string,
  version: string,
  targets: readonly TargetName[],
  signal?: AbortSignal,
): Promise<ArchiveDigests> {
  signal?.throwIfAborted()
  // Rebuilds can leave stale checksums. Verify every archive before replacing the complete list.
  const digests = await verifyDirectory(directory, version, { verifyChecksums: false, targets }, signal)
  signal?.throwIfAborted()
  const staging = await mkdtemp(join(directory, '.checksums-'))
  const destination = join(directory, 'checksums.txt')
  try {
    const temporary = join(staging, 'checksums.txt')
    await writeFile(temporary, checksumContents(digests), {
      encoding: 'ascii',
      flag: 'wx',
      mode: 0o600,
      ...(signal === undefined ? {} : { signal }),
    })
    await checkChecksums(temporary, digests, signal)
    await ordinaryDirectory(directory)
    await ordinaryDestination(destination)
    signal?.throwIfAborted()
    await rename(temporary, destination)
  } finally {
    await rm(staging, { recursive: true, force: true })
  }
  signal?.throwIfAborted()
  console.log(`Wrote ${destination}`)
  return digests
}

/**
 * Build and package the selected targets, then write their checksums.
 *
 * A host builds only its own target by default: the other targets need their own runner, which
 * the release workflow supplies. Every selected target is built before any checksum is written.
 */
export async function buildAll(
  version: string,
  options: ReleaseBuildOptions,
  signal?: AbortSignal,
): Promise<void> {
  signal?.throwIfAborted()
  const targets = options.targets ?? [hostTargetName()]
  const outcomes = await Promise.allSettled(
    targets.map(async (target) => {
      try {
        await build(target, version, options, signal)
      } catch (error) {
        if (
          signal?.aborted &&
          (error === signal.reason || (error instanceof Error && error.name === 'AbortError'))
        ) {
          throw signal.reason
        }
        throw new Error(`Failed to build ${target}: ${errorMessage(error)}`, { cause: error })
      }
    }),
  )
  const failures: Error[] = []
  for (const outcome of outcomes) {
    if (outcome.status === 'rejected') {
      if (signal?.aborted && outcome.reason === signal.reason) continue
      failures.push(outcome.reason instanceof Error ? outcome.reason : new Error(String(outcome.reason)))
    }
  }
  if (failures.length > 0) {
    throw new AggregateError(failures, failures.map((error) => error.message).join('\n'))
  }
  signal?.throwIfAborted()
  await writeLicenseFiles(options, version, signal)
  await checksums(options.output, version, targets, signal)
}

/** Place the release's license material in one archive, replacing any previous one. */
export async function writeLicenseFiles(
  options: ReleaseBuildOptions,
  version: string,
  signal?: AbortSignal,
): Promise<void> {
  signal?.throwIfAborted()
  await mkdir(options.output, { recursive: true })
  await ordinaryDirectory(options.output)
  const entries: { name: string; contents: Buffer }[] = []
  for (const [name, relative] of Object.entries(LICENSE_FILES)) {
    signal?.throwIfAborted()
    let contents: Buffer
    try {
      contents = await readFile(join(options.root, relative))
    } catch (error) {
      throw new Error(
        `missing ${relative}; run \`just licenses\` before building the release (${errorMessage(error)})`,
        { cause: error },
      )
    }
    entries.push({ name, contents })
  }
  const destination = join(options.output, licenseArchiveName(version))
  const staging = await mkdtemp(join(options.output, '.licenses-'))
  try {
    const temporary = join(staging, licenseArchiveName(version))
    await createLicenseArchive(entries, temporary, signal)
    await ordinaryDestination(destination)
    signal?.throwIfAborted()
    await rename(temporary, destination)
  } finally {
    await rm(staging, { recursive: true, force: true })
  }
}
