import { spawnSync } from 'node:child_process'
import { createHash } from 'node:crypto'
import { readFile, writeFile } from 'node:fs/promises'
import { resolve } from 'node:path'
import { parseArgs } from 'node:util'
import { errorMessage } from '../process.ts'
import { REPOSITORY_ROOT } from '../paths.ts'

const HELP = `Regenerate the Iconify collection index Tola pins.

Usage: deno run --allow-read --allow-write --allow-net --allow-run=rustfmt scripts/icons/index.ts [COLLECTION...]

Check each named collection's newest npm release and append the releases that are not pinned yet;
without names, check every collection Iconify publishes. Pinned releases stay in the table.
`

const TABLE = resolve(REPOSITORY_ROOT, 'crates/tola-build/src/icon/iconify/releases.rs')
const ICONIFY_COLLECTIONS = 'https://api.iconify.design/collections'
const NPM_PACKAGE = 'https://registry.npmjs.org/@iconify-json'
const CDN_PACKAGE = 'https://cdn.jsdelivr.net/npm/@iconify-json'
const CONCURRENCY = 8

const HEADER = `// Generated by \`just scripts::icons-index\`; regenerate it instead of editing it.
//
// Releases are in ascending order, so the newest — the release a preset without a version
// resolves to — is last.`

interface PinnedRelease {
  readonly version: string
  readonly sha256: string
}

/** Every release the table pins, keyed by collection. */
function parseTable(source: string): Map<string, PinnedRelease[]> {
  const collections = new Map<string, PinnedRelease[]>()
  const table = source.slice(source.indexOf('INDEXED_COLLECTIONS'))
  for (const block of table.split('IndexedCollection {').slice(1)) {
    const name = block.match(/name:\s*"([^"]*)"/)?.[1]
    if (name === undefined) throw new Error('the table names a collection without a name')
    const releases: PinnedRelease[] = []
    for (const release of block.split('PinnedRelease {').slice(1)) {
      const version = release.match(/version:\s*"([^"]*)"/)?.[1]
      const sha256 = release.match(/sha256:\s*Sha256Digest::from_hex\(\s*"([0-9a-f]{64})"/)?.[1]
      if (version === undefined || sha256 === undefined) {
        throw new Error(`the table pins an incomplete release of ${name}`)
      }
      releases.push({ version, sha256 })
    }
    if (releases.length === 0) throw new Error(`the table pins no release of ${name}`)
    collections.set(name, releases)
  }
  return collections
}

async function readTable(): Promise<Map<string, PinnedRelease[]>> {
  const source = await readFile(TABLE, 'utf8').catch((error: unknown) => {
    if ((error as NodeJS.ErrnoException).code === 'ENOENT') return undefined
    throw error
  })
  return source === undefined ? new Map() : parseTable(source)
}

function renderTable(collections: Map<string, PinnedRelease[]>): string {
  const lines = [
    HEADER,
    '',
    'use super::{IndexedCollection, PinnedRelease};',
    'use crate::config::section::Sha256Digest;',
    '',
    'pub(super) const INDEXED_COLLECTIONS: &[IndexedCollection] = &[',
  ]
  for (
    const [name, releases] of [...collections].sort(([left], [right]) =>
      left === right ? 0 : left < right ? -1 : 1
    )
  ) {
    lines.push('    IndexedCollection {', `        name: ${JSON.stringify(name)},`, '        releases: &[')
    for (const release of releases) {
      lines.push(
        '            PinnedRelease {',
        `                version: ${JSON.stringify(release.version)},`,
        `                sha256: Sha256Digest::from_hex(${JSON.stringify(release.sha256)}),`,
        '            },',
      )
    }
    lines.push('        ],', '    },')
  }
  lines.push('];', '')
  return lines.join('\n')
}

/** Write the table in the formatting `cargo fmt --check` expects. */
async function writeTable(collections: Map<string, PinnedRelease[]>): Promise<void> {
  await writeFile(TABLE, renderTable(collections), 'utf8')
  const formatted = spawnSync('rustfmt', ['--edition', '2024', TABLE], {
    cwd: REPOSITORY_ROOT,
    encoding: 'utf8',
  })
  if (formatted.error) {
    process.stderr.write(`warning: rustfmt is unavailable (${formatted.error.message})\n`)
    return
  }
  if (formatted.status !== 0) {
    throw new Error(`rustfmt refused the generated table: ${(formatted.stderr || formatted.stdout).trim()}`)
  }
}

async function publishedCollections(): Promise<string[]> {
  const response = await fetch(ICONIFY_COLLECTIONS)
  if (!response.ok) throw new Error(`${ICONIFY_COLLECTIONS} answered ${response.status}`)
  const collections = (await response.json()) as Record<string, unknown>
  return Object.keys(collections)
}

async function newestRelease(name: string): Promise<string> {
  const url = `${NPM_PACKAGE}/${encodeURIComponent(name)}/latest`
  const response = await fetch(url)
  if (!response.ok) throw new Error(`${url} answered ${response.status}`)
  const manifest = (await response.json()) as { version?: unknown }
  if (typeof manifest.version !== 'string') throw new Error(`${url} carries no version`)
  return manifest.version
}

/** The digest of one release's bytes, or `undefined` when the package CDN refuses to serve it. */
async function releaseDigest(name: string, version: string): Promise<string | undefined> {
  const url = `${CDN_PACKAGE}/${name}@${version}/icons.json`
  const response = await fetch(url)
  // jsDelivr refuses a file above its size limit, such as `fluent-emoji`'s 103 MB package, so that
  // collection stays without a preset and is declared as `url` with a `sha256` instead.
  if (response.status === 403) return undefined
  if (!response.ok) throw new Error(`${url} answered ${response.status}`)
  const bytes = new Uint8Array(await response.arrayBuffer())
  return createHash('sha256').update(bytes).digest('hex')
}

async function forEachLimited(
  items: readonly string[],
  limit: number,
  run: (item: string) => Promise<void>,
): Promise<void> {
  const queue = [...items]
  const workers = Array.from({ length: Math.min(limit, queue.length) }, async () => {
    while (true) {
      const item = queue.shift()
      if (item === undefined) break
      await run(item)
    }
  })
  await Promise.all(workers)
}

/** Order releases by version, so the newest stays last. */
function compareVersions(left: string, right: string): number {
  const leftParts = left.split(/[.+-]/)
  const rightParts = right.split(/[.+-]/)
  for (let index = 0; index < Math.max(leftParts.length, rightParts.length); index += 1) {
    const leftPart = leftParts[index] ?? ''
    const rightPart = rightParts[index] ?? ''
    const leftNumber = Number.parseInt(leftPart, 10)
    const rightNumber = Number.parseInt(rightPart, 10)
    if (Number.isNaN(leftNumber) || Number.isNaN(rightNumber)) {
      if (leftPart !== rightPart) return leftPart < rightPart ? -1 : 1
    } else if (leftNumber !== rightNumber) {
      return leftNumber < rightNumber ? -1 : 1
    }
  }
  return 0
}

export async function main(args: string[] = process.argv.slice(2)): Promise<void> {
  const parsed = parseArgs({
    args,
    strict: true,
    allowPositionals: true,
    options: { help: { type: 'boolean', short: 'h' } },
  })
  if (parsed.values.help) {
    process.stdout.write(HELP)
    return
  }

  const pinned = await readTable()
  const named = parsed.positionals
  const targets = [
    ...new Set([...(named.length > 0 ? named : await publishedCollections()), ...pinned.keys()]),
  ]
  targets.sort()

  const failures: string[] = []
  let added = 0
  await forEachLimited(targets, CONCURRENCY, async (name) => {
    try {
      const version = await newestRelease(name)
      const releases = pinned.get(name) ?? []
      if (releases.some((release) => release.version === version)) return
      const sha256 = await releaseDigest(name, version)
      if (sha256 === undefined) {
        process.stderr.write(`skipped ${name} ${version}: the package CDN refuses to serve it\n`)
        return
      }
      releases.push({ version, sha256 })
      pinned.set(name, releases)
      added += 1
      process.stdout.write(`${name} ${version}\n`)
    } catch (error) {
      failures.push(`${name}: ${errorMessage(error)}`)
    }
  })

  for (const releases of pinned.values()) {
    releases.sort((left, right) => compareVersions(left.version, right.version))
  }
  await writeTable(pinned)

  if (failures.length > 0) {
    for (const failure of failures) process.stderr.write(`error: ${failure}\n`)
    process.exitCode = 1
    return
  }
  process.stdout.write(`${added} release(s) added; ${pinned.size} collection(s) indexed\n`)
}

if (import.meta.main) await main()
