// Generated by `just scripts::icons-index`; regenerate it instead of editing it.
//
// Releases are in ascending order, so the newest — the release a preset without a version
// resolves to — is last.

use super::{IndexedCollection, PinnedRelease};
use crate::config::section::Sha256Digest;

pub(super) const INDEXED_COLLECTIONS: &[IndexedCollection] = &[
    IndexedCollection {
        name: "academicons",
        releases: &[PinnedRelease {
            version: "1.2.4",
            sha256: Sha256Digest::from_hex(
                "d2fedb2cd0d17f6b47180a273e154adfb6e6670d42c66d3b0b8e484ee24849eb",
            ),
        }],
    },
    IndexedCollection {
        name: "akar-icons",
        releases: &[PinnedRelease {
            version: "1.2.7",
            sha256: Sha256Digest::from_hex(
                "119674a469b44950c8fb31b60ac9f8ec76b704bd2552746ba2860b32c450737c",
            ),
        }],
    },
    IndexedCollection {
        name: "ant-design",
        releases: &[PinnedRelease {
            version: "1.2.9",
            sha256: Sha256Digest::from_hex(
                "9278e9928e768d0bdbbb92166f4e1c97b9c21287c09a9e88cc7419ef03720703",
            ),
        }],
    },
    IndexedCollection {
        name: "arcticons",
        releases: &[PinnedRelease {
            version: "1.2.58",
            sha256: Sha256Digest::from_hex(
                "f6c3c8607947a4137faaf51017fcf6ce5f67cf3517e09eb21d85bbead7b3922b",
            ),
        }],
    },
    IndexedCollection {
        name: "at-icons",
        releases: &[PinnedRelease {
            version: "1.2.3",
            sha256: Sha256Digest::from_hex(
                "dad7a77ecc5aca653841d392e64c578d910bcad846d41d29390a3b99338d8675",
            ),
        }],
    },
    IndexedCollection {
        name: "basil",
        releases: &[PinnedRelease {
            version: "1.2.4",
            sha256: Sha256Digest::from_hex(
                "3c1d22cec5a7ebfbc0267dd2a43da131722a3c6a85a82bf5f79b4a4618246208",
            ),
        }],
    },
    IndexedCollection {
        name: "bi",
        releases: &[PinnedRelease {
            version: "1.2.7",
            sha256: Sha256Digest::from_hex(
                "556b40afedd827ec5d9889345ac10504c4c334c142fba5bbaaf7175a6d754478",
            ),
        }],
    },
    IndexedCollection {
        name: "bitcoin-icons",
        releases: &[PinnedRelease {
            version: "1.2.5",
            sha256: Sha256Digest::from_hex(
                "176758d1eeed3210e538dc48ffeac82442d61829672b5ab2d01b0b5d6f8eba53",
            ),
        }],
    },
    IndexedCollection {
        name: "boxicons",
        releases: &[PinnedRelease {
            version: "1.2.0",
            sha256: Sha256Digest::from_hex(
                "b1f5a1c1cbdc1a030f98fbd9b95295fb104574a88320a5e306598c96acca426f",
            ),
        }],
    },
    IndexedCollection {
        name: "bpmn",
        releases: &[PinnedRelease {
            version: "1.2.1",
            sha256: Sha256Digest::from_hex(
                "89fd88e0370c2f77cb506935303efa85286d88f8b29c11c5d0d9939b5a7b8227",
            ),
        }],
    },
    IndexedCollection {
        name: "brandico",
        releases: &[PinnedRelease {
            version: "1.2.3",
            sha256: Sha256Digest::from_hex(
                "675f910e17cb84e8f40e921dea5179eabe32fb9d97fb6ff00a3c6f1b0a214e2a",
            ),
        }],
    },
    IndexedCollection {
        name: "bx",
        releases: &[PinnedRelease {
            version: "1.2.3",
            sha256: Sha256Digest::from_hex(
                "0672cba5631226189eb1d1f6df624a9aab8f39019e3458adb09761c200a6a0ce",
            ),
        }],
    },
    IndexedCollection {
        name: "bxl",
        releases: &[PinnedRelease {
            version: "1.2.4",
            sha256: Sha256Digest::from_hex(
                "88377a0223cd69631e3e514d9f33e18ec99b205768091618387e2ae368975c09",
            ),
        }],
    },
    IndexedCollection {
        name: "bxs",
        releases: &[PinnedRelease {
            version: "1.2.3",
            sha256: Sha256Digest::from_hex(
                "063965b251bd366adf94316fe3980f74fb5e7dad58e2c67f5876300967c7e2a5",
            ),
        }],
    },
    IndexedCollection {
        name: "bytesize",
        releases: &[PinnedRelease {
            version: "1.2.2",
            sha256: Sha256Digest::from_hex(
                "9d508e4d10e74d92f995a7c19c66940824b3f7f2883c382121fe3b005ce31505",
            ),
        }],
    },
    IndexedCollection {
        name: "carbon",
        releases: &[PinnedRelease {
            version: "1.2.27",
            sha256: Sha256Digest::from_hex(
                "0f0247d037142942711770c67885962adf6479fbd3d2fde2a188ac23b3826d0a",
            ),
        }],
    },
    IndexedCollection {
        name: "catppuccin",
        releases: &[PinnedRelease {
            version: "1.2.17",
            sha256: Sha256Digest::from_hex(
                "a79a874dd61427409b6bea193790eb8fd4afaf154bcd11205f4b252623a11cc4",
            ),
        }],
    },
    IndexedCollection {
        name: "cbi",
        releases: &[PinnedRelease {
            version: "1.2.59",
            sha256: Sha256Digest::from_hex(
                "6cbbe5aa0ba162eeae8f2f05cb04876b88d469db0dda21a0a5ae784243018320",
            ),
        }],
    },
    IndexedCollection {
        name: "charm",
        releases: &[PinnedRelease {
            version: "1.2.3",
            sha256: Sha256Digest::from_hex(
                "a87449bc3236a6387ca596ec2b625fd98216c69ef2d7de63a7117044e6d7f586",
            ),
        }],
    },
    IndexedCollection {
        name: "ci",
        releases: &[PinnedRelease {
            version: "1.2.2",
            sha256: Sha256Digest::from_hex(
                "b71246956f509426241ae9c9cf624b422241f023c3e14eb1bf246b34bf89159c",
            ),
        }],
    },
    IndexedCollection {
        name: "cib",
        releases: &[PinnedRelease {
            version: "1.2.3",
            sha256: Sha256Digest::from_hex(
                "1ca1a73bb741c5fcf73e112d5ce74e5577b43ef7a17facf11529d9356e2a6f82",
            ),
        }],
    },
    IndexedCollection {
        name: "cif",
        releases: &[PinnedRelease {
            version: "1.2.7",
            sha256: Sha256Digest::from_hex(
                "74b75373c7fc6fc4c119d31a394f0538802e19013a6a9350e4e6540e0826d8df",
            ),
        }],
    },
    IndexedCollection {
        name: "cil",
        releases: &[PinnedRelease {
            version: "1.2.3",
            sha256: Sha256Digest::from_hex(
                "fa64221b5f132c5b76dc0ab4050796e2badc09d09bd70869b4d27d372151a383",
            ),
        }],
    },
    IndexedCollection {
        name: "circle-flags",
        releases: &[PinnedRelease {
            version: "1.2.11",
            sha256: Sha256Digest::from_hex(
                "102f1a60ae4485ec9d61d278ebf22c08920513b4712bf2ac358965502fdec210",
            ),
        }],
    },
    IndexedCollection {
        name: "circum",
        releases: &[PinnedRelease {
            version: "1.2.2",
            sha256: Sha256Digest::from_hex(
                "30083714a228c9d90bbec2cbf959a8c8eee5c60d9007fea3e0c61fb0e2baea4d",
            ),
        }],
    },
    IndexedCollection {
        name: "clarity",
        releases: &[PinnedRelease {
            version: "1.2.4",
            sha256: Sha256Digest::from_hex(
                "7e13b0ccd4f129e634d7fed63a54e01d931d77bb7e227d3b4ba8348a64cb81f2",
            ),
        }],
    },
    IndexedCollection {
        name: "codex",
        releases: &[PinnedRelease {
            version: "1.2.0",
            sha256: Sha256Digest::from_hex(
                "5df43a904b3f9c7b43965021132e64bf299430c96723349943fc1f8dd168b81b",
            ),
        }],
    },
    IndexedCollection {
        name: "codicon",
        releases: &[PinnedRelease {
            version: "1.2.73",
            sha256: Sha256Digest::from_hex(
                "fb26e5ed712e21a7f5568d51ff1102b9652ee9bd4c9dbd84a8ba26d0e4dffdc9",
            ),
        }],
    },
    IndexedCollection {
        name: "covid",
        releases: &[PinnedRelease {
            version: "1.2.3",
            sha256: Sha256Digest::from_hex(
                "c8e28f2ffeaae6b31e1e85d64b38d0b2084b4ad351b6c2e066f2f033e7448b20",
            ),
        }],
    },
    IndexedCollection {
        name: "cryptocurrency",
        releases: &[PinnedRelease {
            version: "1.2.3",
            sha256: Sha256Digest::from_hex(
                "2ee165da414ffac7410a83af223a2e8c2075ae02dbce9aab496359a8796fe5c7",
            ),
        }],
    },
    IndexedCollection {
        name: "cryptocurrency-color",
        releases: &[PinnedRelease {
            version: "1.2.4",
            sha256: Sha256Digest::from_hex(
                "a14e4eba39636ba9f81fc60ecf6218bcd0be60b860a02d79b8fcff657841399d",
            ),
        }],
    },
    IndexedCollection {
        name: "cuida",
        releases: &[PinnedRelease {
            version: "1.2.5",
            sha256: Sha256Digest::from_hex(
                "38445135cc40e2db94f7319ad3da9f4de3968fd73dd1809e356ea01a06717590",
            ),
        }],
    },
    IndexedCollection {
        name: "dashicons",
        releases: &[PinnedRelease {
            version: "1.2.1",
            sha256: Sha256Digest::from_hex(
                "9493065886ec18e1fc664b810577b1285d58a8461807e3e91f90a89f27e6b436",
            ),
        }],
    },
    IndexedCollection {
        name: "devicon",
        releases: &[PinnedRelease {
            version: "1.2.67",
            sha256: Sha256Digest::from_hex(
                "40a3a64efd037b44fa55c4238b6b0cbf21b8ee5a8740989067fece5e3e5bcd29",
            ),
        }],
    },
    IndexedCollection {
        name: "devicon-plain",
        releases: &[PinnedRelease {
            version: "1.2.61",
            sha256: Sha256Digest::from_hex(
                "bca364c5cd4ab117cb5d3c1a54cfdd682639910a8b3cd8d4224d4bab95c38866",
            ),
        }],
    },
    IndexedCollection {
        name: "dinkie-icons",
        releases: &[PinnedRelease {
            version: "1.2.0",
            sha256: Sha256Digest::from_hex(
                "82aefadb5dbde8e63ae840fb09b121e78de3dab19f46be11b7601bbbe1c59f8c",
            ),
        }],
    },
    IndexedCollection {
        name: "duo-icons",
        releases: &[PinnedRelease {
            version: "1.2.2",
            sha256: Sha256Digest::from_hex(
                "cd3cf43229d47118fff6128f4c4c44e3d57413797a7d3f14c0dbc3c3cc2ec231",
            ),
        }],
    },
    IndexedCollection {
        name: "ei",
        releases: &[PinnedRelease {
            version: "1.2.2",
            sha256: Sha256Digest::from_hex(
                "31319ee9cee226739d83e0e27ebfd6ea44c9a6383eee1d57d4247e3c5e722795",
            ),
        }],
    },
    IndexedCollection {
        name: "el",
        releases: &[PinnedRelease {
            version: "1.2.2",
            sha256: Sha256Digest::from_hex(
                "ae5667abc4944aa81a3f90e0fe374cc234258dd7469060002604c42ba7664cfd",
            ),
        }],
    },
    IndexedCollection {
        name: "emojione",
        releases: &[PinnedRelease {
            version: "1.2.3",
            sha256: Sha256Digest::from_hex(
                "e9a865faed523a7c3535b5319ae533d09fac1a62b4e96920eb178bb60e707e80",
            ),
        }],
    },
    IndexedCollection {
        name: "emojione-monotone",
        releases: &[PinnedRelease {
            version: "1.2.1",
            sha256: Sha256Digest::from_hex(
                "7b5627535a13e2aac637dcb8817e65554266da1682b3867050eff3db9862d072",
            ),
        }],
    },
    IndexedCollection {
        name: "emojione-v1",
        releases: &[PinnedRelease {
            version: "1.2.3",
            sha256: Sha256Digest::from_hex(
                "7209a500c5607daff4969e5d5ae25da710ab1877c29efec6199d3611a8d5c942",
            ),
        }],
    },
    IndexedCollection {
        name: "entypo",
        releases: &[PinnedRelease {
            version: "1.2.1",
            sha256: Sha256Digest::from_hex(
                "c0d97f36fc64dfaa0cb1b83fd7f43ac44a77a61cd63379700a420aea8b29b033",
            ),
        }],
    },
    IndexedCollection {
        name: "entypo-social",
        releases: &[PinnedRelease {
            version: "1.2.3",
            sha256: Sha256Digest::from_hex(
                "fbdd298ae561838aa64e875f5422c4f4867c5765f34325aab4b63caaf13151eb",
            ),
        }],
    },
    IndexedCollection {
        name: "eos-icons",
        releases: &[PinnedRelease {
            version: "1.2.4",
            sha256: Sha256Digest::from_hex(
                "8fecb6d9f9e1bcf3747bfbdd2484bd978811c04e2fff42e92d44861cf4856ddf",
            ),
        }],
    },
    IndexedCollection {
        name: "ep",
        releases: &[PinnedRelease {
            version: "1.2.4",
            sha256: Sha256Digest::from_hex(
                "845bca245b54323c891bf37d921e518132554ad8777a5c66e406963bfa072d8d",
            ),
        }],
    },
    IndexedCollection {
        name: "et",
        releases: &[PinnedRelease {
            version: "1.2.1",
            sha256: Sha256Digest::from_hex(
                "45853edc6309f9e0c9de2a4aefb1091515c4c41b304c8ac9cf5ec6df0dc1cea6",
            ),
        }],
    },
    IndexedCollection {
        name: "eva",
        releases: &[PinnedRelease {
            version: "1.2.3",
            sha256: Sha256Digest::from_hex(
                "29914198f4cbf8b30a6c97f23bafde5f54b8493d470b92b6070cc51820d4da52",
            ),
        }],
    },
    IndexedCollection {
        name: "f7",
        releases: &[PinnedRelease {
            version: "1.2.2",
            sha256: Sha256Digest::from_hex(
                "3982c624cb43575cdf493aa7d25f6bb50d31abd9e31e93e599cd989823ef297a",
            ),
        }],
    },
    IndexedCollection {
        name: "fa",
        releases: &[PinnedRelease {
            version: "1.2.2",
            sha256: Sha256Digest::from_hex(
                "846452bcf3490253024e6a334484a424135fb5241b53f2df56ffdf27e665eae8",
            ),
        }],
    },
    IndexedCollection {
        name: "fa-brands",
        releases: &[PinnedRelease {
            version: "1.2.2",
            sha256: Sha256Digest::from_hex(
                "87337ae1bfd495ee6a1468318ee1c7f4a749714de93cae121d20ebca14521894",
            ),
        }],
    },
    IndexedCollection {
        name: "fa-regular",
        releases: &[PinnedRelease {
            version: "1.2.2",
            sha256: Sha256Digest::from_hex(
                "9fd11d418e6a89bc3241e3ab6a81aceb37f7880b2ba5981d28a1d74c45e001df",
            ),
        }],
    },
    IndexedCollection {
        name: "fa-solid",
        releases: &[PinnedRelease {
            version: "1.2.2",
            sha256: Sha256Digest::from_hex(
                "47ae9e55e2361304d9795eb001fa6d61a1c42a6f4544c01d686c8c2ca254fbe9",
            ),
        }],
    },
    IndexedCollection {
        name: "fa6-brands",
        releases: &[PinnedRelease {
            version: "1.2.6",
            sha256: Sha256Digest::from_hex(
                "5d548dd51c431f5baa482be3ba63c05a0d910fdd19b7f2d657abdf60dd04dbeb",
            ),
        }],
    },
    IndexedCollection {
        name: "fa6-regular",
        releases: &[PinnedRelease {
            version: "1.2.4",
            sha256: Sha256Digest::from_hex(
                "19295e90a78b82b3df24ed22f9ac590c7bc3cfd13542c08a40c50b4f5e342dbb",
            ),
        }],
    },
    IndexedCollection {
        name: "fa6-solid",
        releases: &[PinnedRelease {
            version: "1.2.4",
            sha256: Sha256Digest::from_hex(
                "0943b4b81864b12d85012a1b9b72ea68376e31acea24dea5075e032353347126",
            ),
        }],
    },
    IndexedCollection {
        name: "fa7-brands",
        releases: &[PinnedRelease {
            version: "1.2.4",
            sha256: Sha256Digest::from_hex(
                "80a9f95928f8a0b06e7d93e0d1520ec5b424c2ff442b9553d8567a12804b3ee3",
            ),
        }],
    },
    IndexedCollection {
        name: "fa7-regular",
        releases: &[PinnedRelease {
            version: "1.2.3",
            sha256: Sha256Digest::from_hex(
                "44f4345f86a40d218a8de41e33191c83646aed1ccd526c2b8e64d7f3e1590768",
            ),
        }],
    },
    IndexedCollection {
        name: "fa7-solid",
        releases: &[PinnedRelease {
            version: "1.2.5",
            sha256: Sha256Digest::from_hex(
                "ad48a3eec6b2e9bdd79fc4c9df04830f06dcb94c7741d2c9d2e5d80f071a1a0a",
            ),
        }],
    },
    IndexedCollection {
        name: "fad",
        releases: &[PinnedRelease {
            version: "1.2.1",
            sha256: Sha256Digest::from_hex(
                "57c81970a54f3f0a64bc9fea5921cf7ca98b965d7a1d9ecef585f8bfbe23e05e",
            ),
        }],
    },
    IndexedCollection {
        name: "famicons",
        releases: &[PinnedRelease {
            version: "1.2.2",
            sha256: Sha256Digest::from_hex(
                "edc82947af18f76e7f7e8c166605ad4eef227e2612e6c2dd3007495f01fbed7d",
            ),
        }],
    },
    IndexedCollection {
        name: "fe",
        releases: &[PinnedRelease {
            version: "1.2.4",
            sha256: Sha256Digest::from_hex(
                "dcd3b297ee96ecdf697fcc3eed09dcaa37170072a1b8cbd0808b845c29276232",
            ),
        }],
    },
    IndexedCollection {
        name: "feather",
        releases: &[PinnedRelease {
            version: "1.2.1",
            sha256: Sha256Digest::from_hex(
                "a72926eae28d7f2aa2f8d567c1c7291aa1d1b28a49440c9d824fbd018eb90b61",
            ),
        }],
    },
    IndexedCollection {
        name: "file-icons",
        releases: &[PinnedRelease {
            version: "1.2.2",
            sha256: Sha256Digest::from_hex(
                "2d8ec1d120a135349359bdd2a0db3e211d682366d4b25b79886d5872162cb93f",
            ),
        }],
    },
    IndexedCollection {
        name: "flag",
        releases: &[PinnedRelease {
            version: "1.2.12",
            sha256: Sha256Digest::from_hex(
                "993d44f221fc7694edcf4d3b379593229cf7bf8de4f0a621e09a8d450d715394",
            ),
        }],
    },
    IndexedCollection {
        name: "flagpack",
        releases: &[PinnedRelease {
            version: "1.2.8",
            sha256: Sha256Digest::from_hex(
                "78f2d021e330a83e5d72fe19b3b308f709a7c91d44d47a2ae7313e496ba9b1e7",
            ),
        }],
    },
    IndexedCollection {
        name: "flat-color-icons",
        releases: &[PinnedRelease {
            version: "1.2.3",
            sha256: Sha256Digest::from_hex(
                "12c081f1d8870c11b82db6be5e494bdc4b30b1bbf4f5010217a29f42147eddc3",
            ),
        }],
    },
    IndexedCollection {
        name: "flat-ui",
        releases: &[PinnedRelease {
            version: "1.2.3",
            sha256: Sha256Digest::from_hex(
                "21cd73b84917d2bc2b4b637aa5e8b7d0daa3f914de5d7709716d01831726e2c7",
            ),
        }],
    },
    IndexedCollection {
        name: "flowbite",
        releases: &[PinnedRelease {
            version: "1.2.7",
            sha256: Sha256Digest::from_hex(
                "c7bbca9e52bea63ce931f4558bbab5f736ac29a5dbc87cd5601bc794b4b9fa52",
            ),
        }],
    },
    IndexedCollection {
        name: "fluent",
        releases: &[PinnedRelease {
            version: "1.2.58",
            sha256: Sha256Digest::from_hex(
                "86397ed4772c5acb3a655f8c16e6f6b2bcc1d1c1ad845f7625b72a992b719c43",
            ),
        }],
    },
    IndexedCollection {
        name: "fluent-color",
        releases: &[PinnedRelease {
            version: "1.2.21",
            sha256: Sha256Digest::from_hex(
                "2a3e9bb2009d1a4c620e76fee74658a78a27c8ae9332830556e9c384ec16e422",
            ),
        }],
    },
    IndexedCollection {
        name: "fluent-emoji-flat",
        releases: &[PinnedRelease {
            version: "1.2.6",
            sha256: Sha256Digest::from_hex(
                "f5f4cf457c0db2ad5a2e42e033e02e0c87d10e43d0164cfffb3bb84914970a63",
            ),
        }],
    },
    IndexedCollection {
        name: "fluent-emoji-high-contrast",
        releases: &[PinnedRelease {
            version: "1.2.6",
            sha256: Sha256Digest::from_hex(
                "c522fb74fef65ccef67b38dfdbf0f3dcd4353339e4b8faec4aa45faf83ed4739",
            ),
        }],
    },
    IndexedCollection {
        name: "fluent-mdl2",
        releases: &[PinnedRelease {
            version: "1.2.1",
            sha256: Sha256Digest::from_hex(
                "bf376ff1056f8e904ba67752f12f241fc742218c72f350c9de5030256ff580ed",
            ),
        }],
    },
    IndexedCollection {
        name: "fontelico",
        releases: &[PinnedRelease {
            version: "1.2.2",
            sha256: Sha256Digest::from_hex(
                "d82377389cc54f1dd357d792fabd78015a290f741bd53800f91a750467b641f5",
            ),
        }],
    },
    IndexedCollection {
        name: "fontisto",
        releases: &[PinnedRelease {
            version: "1.2.1",
            sha256: Sha256Digest::from_hex(
                "988f15e7f2f3acb68ac76259d2d511c5dfdfde2815e8e5d117bf00ccdf0ea8b3",
            ),
        }],
    },
    IndexedCollection {
        name: "formkit",
        releases: &[PinnedRelease {
            version: "1.2.2",
            sha256: Sha256Digest::from_hex(
                "c1e64099b15c0f7b974251cf2a49b57e6912deccd33ca9a3377f1ae073f16105",
            ),
        }],
    },
    IndexedCollection {
        name: "foundation",
        releases: &[PinnedRelease {
            version: "1.2.1",
            sha256: Sha256Digest::from_hex(
                "e999f9fe90fd3a4d1893bfaa7482b464b73590d481253b54de1265b7d79f73b6",
            ),
        }],
    },
    IndexedCollection {
        name: "fxemoji",
        releases: &[PinnedRelease {
            version: "1.2.2",
            sha256: Sha256Digest::from_hex(
                "d8ef67b94a32d0abcd314d1c35db56178eaa8fa8ad71130e312f3460e307c2bf",
            ),
        }],
    },
    IndexedCollection {
        name: "gala",
        releases: &[PinnedRelease {
            version: "1.2.3",
            sha256: Sha256Digest::from_hex(
                "1d84147e94aa183464f69abb49997f432b746b2b130d001ba02c4898350de2e6",
            ),
        }],
    },
    IndexedCollection {
        name: "game-icons",
        releases: &[PinnedRelease {
            version: "1.2.4",
            sha256: Sha256Digest::from_hex(
                "b948029964d549d0ae3b17afead9c9d6f019ddcbdc34f52cb915dc460575c4cd",
            ),
        }],
    },
    IndexedCollection {
        name: "garden",
        releases: &[PinnedRelease {
            version: "1.2.6",
            sha256: Sha256Digest::from_hex(
                "2b2b165e215c7c9ee719a98374be51c748416d7fb1c64c2f057d4f92c40f76d0",
            ),
        }],
    },
    IndexedCollection {
        name: "gcp",
        releases: &[PinnedRelease {
            version: "1.2.2",
            sha256: Sha256Digest::from_hex(
                "54734c385581234eb88a7e9d9f74722767d3c1d601c2584842ee15e3ccd90a7f",
            ),
        }],
    },
    IndexedCollection {
        name: "geo",
        releases: &[PinnedRelease {
            version: "1.2.2",
            sha256: Sha256Digest::from_hex(
                "65468b7a02e89289f6c97ad73367edcd32de169957a5c70880a4780c5ec8cfe8",
            ),
        }],
    },
    IndexedCollection {
        name: "gg",
        releases: &[PinnedRelease {
            version: "1.2.2",
            sha256: Sha256Digest::from_hex(
                "152e68c8c8230092a0b705ad9079d16c44ac99e8afaf5058662f6b56b051e803",
            ),
        }],
    },
    IndexedCollection {
        name: "ginetex",
        releases: &[PinnedRelease {
            version: "1.2.0",
            sha256: Sha256Digest::from_hex(
                "8490d45d61aedee4f3f1047f9c3dfc5025c602e37de8ea709c14a8550507af60",
            ),
        }],
    },
    IndexedCollection {
        name: "gis",
        releases: &[PinnedRelease {
            version: "1.2.5",
            sha256: Sha256Digest::from_hex(
                "a9185a080a36800035ba3b2acbd0f4bac4bfb33cd676b6fd40338c15f844528d",
            ),
        }],
    },
    IndexedCollection {
        name: "glyphs",
        releases: &[PinnedRelease {
            version: "1.2.0",
            sha256: Sha256Digest::from_hex(
                "19664474c4af6ba4983c782187c2c311d96676e974831ae8705bfecf0dd0d9d9",
            ),
        }],
    },
    IndexedCollection {
        name: "glyphs-poly",
        releases: &[PinnedRelease {
            version: "1.2.0",
            sha256: Sha256Digest::from_hex(
                "375a100be74aeeff29a26f5e8a39a63f23db12ef14d8c239971cf94da27f9007",
            ),
        }],
    },
    IndexedCollection {
        name: "gravity-ui",
        releases: &[PinnedRelease {
            version: "1.2.14",
            sha256: Sha256Digest::from_hex(
                "5867db57b39bb3604ab8731ef0ed91342e6b5ee20d3c413a8e040b6a1d7d5133",
            ),
        }],
    },
    IndexedCollection {
        name: "griddy-icons",
        releases: &[PinnedRelease {
            version: "1.2.0",
            sha256: Sha256Digest::from_hex(
                "fecebdef09247ac1412609c402063d12be9a844548dc20ec2767aa034f0bfeca",
            ),
        }],
    },
    IndexedCollection {
        name: "gridicons",
        releases: &[PinnedRelease {
            version: "1.2.5",
            sha256: Sha256Digest::from_hex(
                "b7d064238df35cd5c3676990fd671fb2cfb6492852b7eac754b1e9da6ce476ab",
            ),
        }],
    },
    IndexedCollection {
        name: "grommet-icons",
        releases: &[PinnedRelease {
            version: "1.2.4",
            sha256: Sha256Digest::from_hex(
                "cf41db2273bc3c3a41b0f278e968e86f347271b59d4c1031433c5519a0028aa1",
            ),
        }],
    },
    IndexedCollection {
        name: "guidance",
        releases: &[PinnedRelease {
            version: "1.2.2",
            sha256: Sha256Digest::from_hex(
                "bfb8a2df50eaee15c1b1dd7f8b4936b35f243933ab55acd81f356d6bd800df41",
            ),
        }],
    },
    IndexedCollection {
        name: "healthicons",
        releases: &[PinnedRelease {
            version: "1.2.13",
            sha256: Sha256Digest::from_hex(
                "9abb051a436298d54161b5b633059651820f4546bc0468e0f5eea5d6e25ddb25",
            ),
        }],
    },
    IndexedCollection {
        name: "heroicons",
        releases: &[PinnedRelease {
            version: "1.2.3",
            sha256: Sha256Digest::from_hex(
                "a132691d3f539ab797fc009a3467d86f558429612657f1f0cad31b4fdad63cd7",
            ),
        }],
    },
    IndexedCollection {
        name: "heroicons-outline",
        releases: &[PinnedRelease {
            version: "1.2.1",
            sha256: Sha256Digest::from_hex(
                "2123a5f693281bb05ac8deaca0df39115b1f78677f62c8fbee23f1694c60ca3b",
            ),
        }],
    },
    IndexedCollection {
        name: "heroicons-solid",
        releases: &[PinnedRelease {
            version: "1.2.1",
            sha256: Sha256Digest::from_hex(
                "dc1db4814c3f8f56a8493900a50199712f1229e978bd7b9ff7f1ee321f608aa5",
            ),
        }],
    },
    IndexedCollection {
        name: "hugeicons",
        releases: &[PinnedRelease {
            version: "1.2.35",
            sha256: Sha256Digest::from_hex(
                "8d76e777b9a32a3bc17badc6c8213cd4b8155ea3bb7578828e40cf9d6d40385f",
            ),
        }],
    },
    IndexedCollection {
        name: "humbleicons",
        releases: &[PinnedRelease {
            version: "1.2.20",
            sha256: Sha256Digest::from_hex(
                "a808bfbbf37e1993103d93d3e44f43fd9f56d89aeec495babad9ffd75f57c595",
            ),
        }],
    },
    IndexedCollection {
        name: "ic",
        releases: &[PinnedRelease {
            version: "1.2.4",
            sha256: Sha256Digest::from_hex(
                "984bd565f7d3fc634ccd7a3727beb1d8ee0ff632053a874c4ffe619980def2ad",
            ),
        }],
    },
    IndexedCollection {
        name: "icomoon-free",
        releases: &[PinnedRelease {
            version: "1.2.1",
            sha256: Sha256Digest::from_hex(
                "abc2de0bd560af28b0bc4d908576dd0144cdb5bd7fb1cf7674c9ec6050b9be45",
            ),
        }],
    },
    IndexedCollection {
        name: "icon-park",
        releases: &[PinnedRelease {
            version: "1.2.4",
            sha256: Sha256Digest::from_hex(
                "768e3fb9207a8dfb0ba231714f5d6a1327dbc25ed881477c6f576249a0d54a4f",
            ),
        }],
    },
    IndexedCollection {
        name: "icon-park-outline",
        releases: &[PinnedRelease {
            version: "1.2.4",
            sha256: Sha256Digest::from_hex(
                "873be980481f0ea595bc56d158d6b6f0adc6444c67f9b0a7b00a97e23a797638",
            ),
        }],
    },
    IndexedCollection {
        name: "icon-park-solid",
        releases: &[PinnedRelease {
            version: "1.2.4",
            sha256: Sha256Digest::from_hex(
                "f93f5526f4f3400e8a0b02d4d81e31b4cc23b29c0414594c031274a4aeb15be2",
            ),
        }],
    },
    IndexedCollection {
        name: "icon-park-twotone",
        releases: &[PinnedRelease {
            version: "1.2.4",
            sha256: Sha256Digest::from_hex(
                "4b1d198b618c756908e53e3953f03ed71d4fc8d32c65887abd35cad329112a6e",
            ),
        }],
    },
    IndexedCollection {
        name: "iconamoon",
        releases: &[PinnedRelease {
            version: "1.2.2",
            sha256: Sha256Digest::from_hex(
                "339f728bb7009a245f9008615b53aac62284f3e8d0fe1fcf2e941b8bc17e2abd",
            ),
        }],
    },
    IndexedCollection {
        name: "iconmind",
        releases: &[PinnedRelease {
            version: "1.2.2",
            sha256: Sha256Digest::from_hex(
                "bbed0ff9adbb549242a038163f600c1ced157cb96c987a36af87705e3edfcc6b",
            ),
        }],
    },
    IndexedCollection {
        name: "iconoir",
        releases: &[PinnedRelease {
            version: "1.2.11",
            sha256: Sha256Digest::from_hex(
                "e1788785bf4708ed39bce81df9d9514090b79b1d7b33fc15e969a95a1acf5eb9",
            ),
        }],
    },
    IndexedCollection {
        name: "icons8",
        releases: &[PinnedRelease {
            version: "1.2.1",
            sha256: Sha256Digest::from_hex(
                "32eaf3e63fb23388da1ca0f3056f7858a34bc20183f75df0435a897bcb8ea917",
            ),
        }],
    },
    IndexedCollection {
        name: "il",
        releases: &[PinnedRelease {
            version: "1.2.2",
            sha256: Sha256Digest::from_hex(
                "52c2dc1088f5a0f3d9e4ca9b02e7dbb82d86195d1fbb0011b25ec9c90648304f",
            ),
        }],
    },
    IndexedCollection {
        name: "ion",
        releases: &[PinnedRelease {
            version: "1.2.7",
            sha256: Sha256Digest::from_hex(
                "e4d38d34c65c9f70de72e6d95ae23858831356d178227ec4c931dc423345fc2f",
            ),
        }],
    },
    IndexedCollection {
        name: "iwwa",
        releases: &[PinnedRelease {
            version: "1.2.1",
            sha256: Sha256Digest::from_hex(
                "2ac3b4d1b05c38651bf416eb0f9b7ea945b7ecb82c9338bbf75de3a5a4f7d8e8",
            ),
        }],
    },
    IndexedCollection {
        name: "ix",
        releases: &[PinnedRelease {
            version: "1.2.12",
            sha256: Sha256Digest::from_hex(
                "fe4e24bce276a430aed1dedd188742a02ce309a1ee9c2145814734d016c39f53",
            ),
        }],
    },
    IndexedCollection {
        name: "jam",
        releases: &[PinnedRelease {
            version: "1.2.3",
            sha256: Sha256Digest::from_hex(
                "1c8134ac6cf93c61051d55996af1c186a2c1973bb9005739558fe6a23a6e44ce",
            ),
        }],
    },
    IndexedCollection {
        name: "k8s",
        releases: &[PinnedRelease {
            version: "1.2.1",
            sha256: Sha256Digest::from_hex(
                "4bcc2fa31760db6f7cf313747f2fca69375271af3eb005f9687eab9422b594aa",
            ),
        }],
    },
    IndexedCollection {
        name: "keyline-icons",
        releases: &[PinnedRelease {
            version: "1.2.8",
            sha256: Sha256Digest::from_hex(
                "64413baa157cc8dc01a363a77bfeaeff193a251de6b1abccd20aa73690bd9242",
            ),
        }],
    },
    IndexedCollection {
        name: "la",
        releases: &[PinnedRelease {
            version: "1.2.1",
            sha256: Sha256Digest::from_hex(
                "48fa4a47a5a3a2e5a029440d19052a19971fbc79cc692359fc3beb492be33fc0",
            ),
        }],
    },
    IndexedCollection {
        name: "lets-icons",
        releases: &[PinnedRelease {
            version: "1.2.2",
            sha256: Sha256Digest::from_hex(
                "df423ec5253986cd5bf3a65eb998f300f50919b2c2226259ab325710c8280b33",
            ),
        }],
    },
    IndexedCollection {
        name: "line-md",
        releases: &[PinnedRelease {
            version: "1.2.16",
            sha256: Sha256Digest::from_hex(
                "76ce15e777d4867e24fad6925bc03ed5ec2c6dd29ca652fe6e1d38918e6a2ad9",
            ),
        }],
    },
    IndexedCollection {
        name: "lineicons",
        releases: &[PinnedRelease {
            version: "1.2.6",
            sha256: Sha256Digest::from_hex(
                "162d533fbddac8f4f3004d04ef95a93544178b2befccef9c3e888308e1a27c97",
            ),
        }],
    },
    IndexedCollection {
        name: "logos",
        releases: &[PinnedRelease {
            version: "1.2.14",
            sha256: Sha256Digest::from_hex(
                "3eba737ec35e422b9050933a4efb461ad5d4e6ccce781bfbe14ceba533538e50",
            ),
        }],
    },
    IndexedCollection {
        name: "ls",
        releases: &[PinnedRelease {
            version: "1.2.2",
            sha256: Sha256Digest::from_hex(
                "f5cdb32cba49991bd6e735d242611df670d1969d5cee26c516ed665bbeed5492",
            ),
        }],
    },
    IndexedCollection {
        name: "lsicon",
        releases: &[PinnedRelease {
            version: "1.2.5",
            sha256: Sha256Digest::from_hex(
                "ef77bf168079094eaea3790aaf6af4b5aedc563461f0611506e2b2a3b4201b37",
            ),
        }],
    },
    IndexedCollection {
        name: "lucide",
        releases: &[PinnedRelease {
            version: "1.2.136",
            sha256: Sha256Digest::from_hex(
                "8cd40caac3fd9882dd9380b0e0fffa1acaa3c8bd86c40c2b70d764560e707375",
            ),
        }],
    },
    IndexedCollection {
        name: "lucide-lab",
        releases: &[PinnedRelease {
            version: "1.2.3",
            sha256: Sha256Digest::from_hex(
                "07cb24547776acae210f54213d0ca77b066a359446bafd775a9fa56f941975d1",
            ),
        }],
    },
    IndexedCollection {
        name: "mage",
        releases: &[PinnedRelease {
            version: "1.2.4",
            sha256: Sha256Digest::from_hex(
                "61b4c02c3254bbbd5173ac422a767e3f3b060673ef116894949d6664e10a676f",
            ),
        }],
    },
    IndexedCollection {
        name: "majesticons",
        releases: &[PinnedRelease {
            version: "1.2.5",
            sha256: Sha256Digest::from_hex(
                "a3925452549838f9fb0eec49c2c22b0639550f238e8c6d00728155c14b0b78eb",
            ),
        }],
    },
    IndexedCollection {
        name: "maki",
        releases: &[PinnedRelease {
            version: "1.2.5",
            sha256: Sha256Digest::from_hex(
                "aa5b63aab3dfc7939360f26156d495e289648906a4b721fd41368d7bc9576fac",
            ),
        }],
    },
    IndexedCollection {
        name: "map",
        releases: &[PinnedRelease {
            version: "1.2.2",
            sha256: Sha256Digest::from_hex(
                "6249f6b4918e5a6e78ee76839a5be5912aeac885580955b8b2fe840b42cd36ba",
            ),
        }],
    },
    IndexedCollection {
        name: "marketeq",
        releases: &[PinnedRelease {
            version: "1.2.2",
            sha256: Sha256Digest::from_hex(
                "0e8fda6d3af181f99f2684a201477f601d10587389d02dc4f8066e595a0fd021",
            ),
        }],
    },
    IndexedCollection {
        name: "material-icon-theme",
        releases: &[PinnedRelease {
            version: "1.2.70",
            sha256: Sha256Digest::from_hex(
                "fdaae0137875baa76fd8e1ebf05e80d8c91ef2850c560cb1884da5870f8092c7",
            ),
        }],
    },
    IndexedCollection {
        name: "material-symbols",
        releases: &[PinnedRelease {
            version: "1.2.93",
            sha256: Sha256Digest::from_hex(
                "891b1209b0c27f7995a58bd4ae55fe7f2b8607791f164244f27e70e1cae52d51",
            ),
        }],
    },
    IndexedCollection {
        name: "material-symbols-light",
        releases: &[PinnedRelease {
            version: "1.2.94",
            sha256: Sha256Digest::from_hex(
                "50f972ca896fadabb8347a10aeabafa474700630805a98929cc1b5f4960d961c",
            ),
        }],
    },
    IndexedCollection {
        name: "mdi",
        releases: &[PinnedRelease {
            version: "1.2.3",
            sha256: Sha256Digest::from_hex(
                "f38bcea6e945f01004384c1dbb66ddb2a538d81b7f6af3cf6b95fc603603833a",
            ),
        }],
    },
    IndexedCollection {
        name: "mdi-light",
        releases: &[PinnedRelease {
            version: "1.2.2",
            sha256: Sha256Digest::from_hex(
                "8e97578d366ce1ee784b2aa323febb021814db873c45f8c55a1063e5b5b0b0e9",
            ),
        }],
    },
    IndexedCollection {
        name: "medical-icon",
        releases: &[PinnedRelease {
            version: "1.2.0",
            sha256: Sha256Digest::from_hex(
                "dae85ffb830d749e12ba1f3f9d0b92d6a85457b1e05648d9c0c54007364b938c",
            ),
        }],
    },
    IndexedCollection {
        name: "memory",
        releases: &[PinnedRelease {
            version: "1.2.2",
            sha256: Sha256Digest::from_hex(
                "c3a103220b008ff046c549dac54b8d83179a14c9811d68353208c3f54445c5dd",
            ),
        }],
    },
    IndexedCollection {
        name: "meteocons",
        releases: &[PinnedRelease {
            version: "1.2.4",
            sha256: Sha256Digest::from_hex(
                "73de3680ddfb3c2cb7434724b7e4c756f9de3b574bf451facb96a13b6ddd808a",
            ),
        }],
    },
    IndexedCollection {
        name: "meteor-icons",
        releases: &[PinnedRelease {
            version: "1.2.8",
            sha256: Sha256Digest::from_hex(
                "a5d7499cb4a9da698c5e821153a12a3594491426e2587f8d09ba6f95ae8d197d",
            ),
        }],
    },
    IndexedCollection {
        name: "mi",
        releases: &[PinnedRelease {
            version: "1.2.2",
            sha256: Sha256Digest::from_hex(
                "0c30d83296e57aca8241dbac8ff04efeb8becbcab29692fce1bb3e224876143e",
            ),
        }],
    },
    IndexedCollection {
        name: "mingcute",
        releases: &[PinnedRelease {
            version: "1.2.8",
            sha256: Sha256Digest::from_hex(
                "062cd8a1d3bf1f60173784352c0b679a2b747945230aa8dac4d59f66f0787ed7",
            ),
        }],
    },
    IndexedCollection {
        name: "mono-icons",
        releases: &[PinnedRelease {
            version: "1.2.0",
            sha256: Sha256Digest::from_hex(
                "b834093f9894d12cb69d95963444fc55a5b50d47d3d57f1c93a2e782d7d7072b",
            ),
        }],
    },
    IndexedCollection {
        name: "mynaui",
        releases: &[PinnedRelease {
            version: "1.2.19",
            sha256: Sha256Digest::from_hex(
                "11988e3614646dcde7bee297024c98efc791cd752acea505e0e764e4d0478d73",
            ),
        }],
    },
    IndexedCollection {
        name: "nimbus",
        releases: &[PinnedRelease {
            version: "1.2.1",
            sha256: Sha256Digest::from_hex(
                "b1be60b10e6873715f33dc326fb9a7874a779fd3035b387e8fded657f8336fdd",
            ),
        }],
    },
    IndexedCollection {
        name: "nonicons",
        releases: &[PinnedRelease {
            version: "1.2.2",
            sha256: Sha256Digest::from_hex(
                "708726b3a8270ab693aa82413314e272cac9a6b9fa6b44adc0760b32d00992a4",
            ),
        }],
    },
    IndexedCollection {
        name: "noto",
        releases: &[PinnedRelease {
            version: "1.2.8",
            sha256: Sha256Digest::from_hex(
                "7f2e0c1a48117b0414b7a9a611f3029faa41398512f12e77e74f99b784b79ba1",
            ),
        }],
    },
    IndexedCollection {
        name: "noto-v1",
        releases: &[PinnedRelease {
            version: "1.2.5",
            sha256: Sha256Digest::from_hex(
                "ce70d8aa90345cf389875c3571ecd245bd943401822a0c5a0f62336bf8487333",
            ),
        }],
    },
    IndexedCollection {
        name: "nrk",
        releases: &[PinnedRelease {
            version: "1.2.11",
            sha256: Sha256Digest::from_hex(
                "44535b231fa06aa1812f53a774364ff2217064ab636127c79df3b7e09ec1a043",
            ),
        }],
    },
    IndexedCollection {
        name: "octicon",
        releases: &[PinnedRelease {
            version: "1.2.36",
            sha256: Sha256Digest::from_hex(
                "e3f79ec08b924d9d5f8d9582a6713fba005ebf014fd980100bde54aa4ed75518",
            ),
        }],
    },
    IndexedCollection {
        name: "oi",
        releases: &[PinnedRelease {
            version: "1.2.1",
            sha256: Sha256Digest::from_hex(
                "07a1ad4ba3f5d6eb4a5c08e7155c551edef1e3653d7896706ee0ffd42e771481",
            ),
        }],
    },
    IndexedCollection {
        name: "ooui",
        releases: &[PinnedRelease {
            version: "1.2.24",
            sha256: Sha256Digest::from_hex(
                "71fc8555580156c78d700f68a0972a770e13cb02053896bef09d53c651b43938",
            ),
        }],
    },
    IndexedCollection {
        name: "openmoji",
        releases: &[PinnedRelease {
            version: "1.2.29",
            sha256: Sha256Digest::from_hex(
                "7075331faab544067dbff4236471dd378bb5410aa05799a8a343c9ebf5c5984c",
            ),
        }],
    },
    IndexedCollection {
        name: "osmic",
        releases: &[PinnedRelease {
            version: "1.2.0",
            sha256: Sha256Digest::from_hex(
                "a09929ad92182a2f4a7db10bc99fc1044551479b0afb03ca3e2c4d2a07e8f6bd",
            ),
        }],
    },
    IndexedCollection {
        name: "oui",
        releases: &[PinnedRelease {
            version: "1.2.6",
            sha256: Sha256Digest::from_hex(
                "c91326e6469153b037d93fefad4c93ee8674b99d5bacecbae1ae6b9455de5bff",
            ),
        }],
    },
    IndexedCollection {
        name: "pajamas",
        releases: &[PinnedRelease {
            version: "1.2.15",
            sha256: Sha256Digest::from_hex(
                "d9da1d7b227234832dc9b88633bc8f95c1432019074e3b9b67f84803f65054ad",
            ),
        }],
    },
    IndexedCollection {
        name: "pepicons",
        releases: &[PinnedRelease {
            version: "1.2.0",
            sha256: Sha256Digest::from_hex(
                "6ae9661a2967b3c8ae3c1af1014fb4b55b72ee4f474ccd10dcf9992504297eeb",
            ),
        }],
    },
    IndexedCollection {
        name: "pepicons-pencil",
        releases: &[PinnedRelease {
            version: "1.2.4",
            sha256: Sha256Digest::from_hex(
                "cefc0e8ff70ebc2b83cc2f0ad45853e36ee1eaebf099e07fb21c4b3ae298d25b",
            ),
        }],
    },
    IndexedCollection {
        name: "pepicons-pop",
        releases: &[PinnedRelease {
            version: "1.2.4",
            sha256: Sha256Digest::from_hex(
                "ced5c3bbcb7324b04fe75562ad0e82083e4b6cfb0d578b37c777369be9eb1ce8",
            ),
        }],
    },
    IndexedCollection {
        name: "pepicons-print",
        releases: &[PinnedRelease {
            version: "1.2.2",
            sha256: Sha256Digest::from_hex(
                "3a15bfe210caceacf87ab4b1465b350b29a3180251aeb9e2777e556097448dc6",
            ),
        }],
    },
    IndexedCollection {
        name: "ph",
        releases: &[PinnedRelease {
            version: "1.2.2",
            sha256: Sha256Digest::from_hex(
                "cf75b3541b06b3bb40f9e40880d4fb34a648c02c4bc8181f49b7db40e0f53d3c",
            ),
        }],
    },
    IndexedCollection {
        name: "picon",
        releases: &[PinnedRelease {
            version: "1.2.0",
            sha256: Sha256Digest::from_hex(
                "78595446653ceb015ddd34fe98431add1a0c5f29ec0462aedc366996ae058b40",
            ),
        }],
    },
    IndexedCollection {
        name: "pinhead",
        releases: &[PinnedRelease {
            version: "1.2.31",
            sha256: Sha256Digest::from_hex(
                "c6eaf068fd6e54a54aa54f1b8425146339c72fb560addc34339b6732007bbf95",
            ),
        }],
    },
    IndexedCollection {
        name: "pixel",
        releases: &[PinnedRelease {
            version: "1.2.2",
            sha256: Sha256Digest::from_hex(
                "0c1f5b561adaaa9ac3617f2f19f7c75802ed3fd5629b7036add8e9aa70b32700",
            ),
        }],
    },
    IndexedCollection {
        name: "pixelarticons",
        releases: &[PinnedRelease {
            version: "1.2.9",
            sha256: Sha256Digest::from_hex(
                "49b009b520f4042ebb9190b0fcaa5b2f5ccb4572e04efa4f8b1c0d1e671559cb",
            ),
        }],
    },
    IndexedCollection {
        name: "prime",
        releases: &[PinnedRelease {
            version: "1.2.5",
            sha256: Sha256Digest::from_hex(
                "b1713cc36f00665777cfabce48aafd9a4f66e67c356a3405d8e26ab61bf83fce",
            ),
        }],
    },
    IndexedCollection {
        name: "proicons",
        releases: &[PinnedRelease {
            version: "1.2.20",
            sha256: Sha256Digest::from_hex(
                "c98c0ca1eaadbb2d5f5f0d492761dba7e8f5d52b81686b308a859a8ec4be4c48",
            ),
        }],
    },
    IndexedCollection {
        name: "ps",
        releases: &[PinnedRelease {
            version: "1.2.0",
            sha256: Sha256Digest::from_hex(
                "1b431fac342f78a166eb17bbec28f146b3a08c363de793b5a523ed5d43c67b56",
            ),
        }],
    },
    IndexedCollection {
        name: "qlementine-icons",
        releases: &[PinnedRelease {
            version: "1.2.16",
            sha256: Sha256Digest::from_hex(
                "5e0706335c7165b898b77ec6e636cdfd8c7cd274b503b98ca86095fa858afe8e",
            ),
        }],
    },
    IndexedCollection {
        name: "quill",
        releases: &[PinnedRelease {
            version: "1.2.4",
            sha256: Sha256Digest::from_hex(
                "b64e318ed3d4c5c9244ce54a63191cb1fde28380967a85463bd44c72e83f46a5",
            ),
        }],
    },
    IndexedCollection {
        name: "radix-icons",
        releases: &[PinnedRelease {
            version: "1.2.6",
            sha256: Sha256Digest::from_hex(
                "7590463216db2907313b6ca239e5e1975c36c5bd2735d044dc8be264ff1ff751",
            ),
        }],
    },
    IndexedCollection {
        name: "raphael",
        releases: &[PinnedRelease {
            version: "1.2.1",
            sha256: Sha256Digest::from_hex(
                "913dc9adaf9a594394b1c0d77447a2a1b3d8f205218655f646daf939ef8202ef",
            ),
        }],
    },
    IndexedCollection {
        name: "reicon",
        releases: &[PinnedRelease {
            version: "1.2.5",
            sha256: Sha256Digest::from_hex(
                "8f05051725826399eed28a5a8f9de79c5e9dc3d23ba042fb1dff01722bb7b55c",
            ),
        }],
    },
    IndexedCollection {
        name: "ri",
        releases: &[PinnedRelease {
            version: "1.2.10",
            sha256: Sha256Digest::from_hex(
                "4a0e1c82c0faf914881f4776dc1bdfb4efcde4c28f249ceec17bd11c1d749994",
            ),
        }],
    },
    IndexedCollection {
        name: "rivet-icons",
        releases: &[PinnedRelease {
            version: "1.2.2",
            sha256: Sha256Digest::from_hex(
                "e6885eebcc58ebb8d97f81277024aac851c2ee9675e32344b6de7687f73cdf80",
            ),
        }],
    },
    IndexedCollection {
        name: "roentgen",
        releases: &[PinnedRelease {
            version: "1.2.26",
            sha256: Sha256Digest::from_hex(
                "73b8d24885c7c6b829e269a07665e58205a8b4e2ef1a325e2f9279ffb982afcf",
            ),
        }],
    },
    IndexedCollection {
        name: "selfhst",
        releases: &[PinnedRelease {
            version: "1.2.21",
            sha256: Sha256Digest::from_hex(
                "5c409ac19ed7c6fea0e6ad21b12019566f2110c68227a2792461d76e69e1b590",
            ),
        }],
    },
    IndexedCollection {
        name: "si",
        releases: &[PinnedRelease {
            version: "1.2.17",
            sha256: Sha256Digest::from_hex(
                "a11ad0ea2da81dedb47ab527edcab27fdddf0b0000e88cd3ab180588292ca2eb",
            ),
        }],
    },
    IndexedCollection {
        name: "si-glyph",
        releases: &[PinnedRelease {
            version: "1.2.2",
            sha256: Sha256Digest::from_hex(
                "9594e7f8bf7acf47a26626529388d02c5f17ad860cbf8678236bcdd032d144f1",
            ),
        }],
    },
    IndexedCollection {
        name: "sidekickicons",
        releases: &[PinnedRelease {
            version: "1.2.1",
            sha256: Sha256Digest::from_hex(
                "abdb67e3a21be4ff8bd18ca6ea28f61d890e46c0babac36f688c73a7547dceaf",
            ),
        }],
    },
    IndexedCollection {
        name: "simple-icons",
        releases: &[PinnedRelease {
            version: "1.2.97",
            sha256: Sha256Digest::from_hex(
                "c7b597632f2aac9ceaf8d69eff7836c3e1c950e2c220f7bdacc815a5dd940bf0",
            ),
        }],
    },
    IndexedCollection {
        name: "simple-line-icons",
        releases: &[PinnedRelease {
            version: "1.2.1",
            sha256: Sha256Digest::from_hex(
                "6f48366a2fbf050d426e31bbfdb0bf465fc0b8dbcd1ef56a22adbad12646a0b3",
            ),
        }],
    },
    IndexedCollection {
        name: "skill-icons",
        releases: &[PinnedRelease {
            version: "1.2.4",
            sha256: Sha256Digest::from_hex(
                "7abf0af7f0f86a5db0aab21a4673962a73d7ab10939cb5952410c65b988155f1",
            ),
        }],
    },
    IndexedCollection {
        name: "solar",
        releases: &[PinnedRelease {
            version: "1.2.12",
            sha256: Sha256Digest::from_hex(
                "02c0032f6a96c5c6f3ad9e3f5b984303d74ef0e20657499f297ca39252bda71e",
            ),
        }],
    },
    IndexedCollection {
        name: "stash",
        releases: &[PinnedRelease {
            version: "1.2.4",
            sha256: Sha256Digest::from_hex(
                "756deadca0f153475ce1a2b8612e88ca28e661d5f77720660c1ac5b2bbb28b07",
            ),
        }],
    },
    IndexedCollection {
        name: "streamline",
        releases: &[PinnedRelease {
            version: "1.2.5",
            sha256: Sha256Digest::from_hex(
                "430a77f3bdb7a833f7f3c6d85cc32f560135bab84aab4c837fabbdecaf5a878b",
            ),
        }],
    },
    IndexedCollection {
        name: "streamline-block",
        releases: &[PinnedRelease {
            version: "1.2.0",
            sha256: Sha256Digest::from_hex(
                "d4ed76f712d3da4f66da8e3afcf8d1423e09a925248b65f00bb0551ee3d6af7f",
            ),
        }],
    },
    IndexedCollection {
        name: "streamline-color",
        releases: &[PinnedRelease {
            version: "1.2.2",
            sha256: Sha256Digest::from_hex(
                "c25dd355925b4fde148ec483f5d6ee0aa3cd7a96615c9f0ee7fb7959e0caca83",
            ),
        }],
    },
    IndexedCollection {
        name: "streamline-cyber",
        releases: &[PinnedRelease {
            version: "1.2.2",
            sha256: Sha256Digest::from_hex(
                "22a994b0760533884d115fd7e983fa6c8ef6edf601d5afbf82788dd02e9ddb13",
            ),
        }],
    },
    IndexedCollection {
        name: "streamline-cyber-color",
        releases: &[PinnedRelease {
            version: "1.2.2",
            sha256: Sha256Digest::from_hex(
                "b7c74bce159f899464bf99de0a96fc7157326cfddb40b5461acc5120b0cf7e69",
            ),
        }],
    },
    IndexedCollection {
        name: "streamline-emojis",
        releases: &[PinnedRelease {
            version: "1.2.4",
            sha256: Sha256Digest::from_hex(
                "d3cb7afee48544af5657a92951cff18ffef7b150a13b3df1bb54b8c0757bfad6",
            ),
        }],
    },
    IndexedCollection {
        name: "streamline-flex",
        releases: &[PinnedRelease {
            version: "1.2.3",
            sha256: Sha256Digest::from_hex(
                "f9a356783cc3e9b422220b08433d77292be94ade719baa3441f5bff3e9bd23f6",
            ),
        }],
    },
    IndexedCollection {
        name: "streamline-flex-color",
        releases: &[PinnedRelease {
            version: "1.2.2",
            sha256: Sha256Digest::from_hex(
                "d4860243383d8359ec48e24693b147311b690a9847240d7d72ef75c7cff604e7",
            ),
        }],
    },
    IndexedCollection {
        name: "streamline-freehand",
        releases: &[PinnedRelease {
            version: "1.2.1",
            sha256: Sha256Digest::from_hex(
                "e6aee38eeab9f781fea31b26d740c0ee7fb33e93e1ee8e23bde48da3d2abd4d0",
            ),
        }],
    },
    IndexedCollection {
        name: "streamline-freehand-color",
        releases: &[PinnedRelease {
            version: "1.2.2",
            sha256: Sha256Digest::from_hex(
                "fe1bfb7917bcc71553e1cb1904933aa5e78df040683a004d5012fb738d216074",
            ),
        }],
    },
    IndexedCollection {
        name: "streamline-kameleon-color",
        releases: &[PinnedRelease {
            version: "1.2.2",
            sha256: Sha256Digest::from_hex(
                "f348df85668276969c44d1275eea0b28befdb7edb7de15f0a82b33bfbcf46b38",
            ),
        }],
    },
    IndexedCollection {
        name: "streamline-logos",
        releases: &[PinnedRelease {
            version: "1.2.0",
            sha256: Sha256Digest::from_hex(
                "b6863f5bc98871dadf445f548a85b30c2cb790d22927450b459fec97e044efbf",
            ),
        }],
    },
    IndexedCollection {
        name: "streamline-pixel",
        releases: &[PinnedRelease {
            version: "1.2.0",
            sha256: Sha256Digest::from_hex(
                "a58e9a743be7b7a685c7db26c7bf9e746dd1186dd20b9a90759273a415eaae7e",
            ),
        }],
    },
    IndexedCollection {
        name: "streamline-plump",
        releases: &[PinnedRelease {
            version: "1.2.0",
            sha256: Sha256Digest::from_hex(
                "90bb8013ea2745847b53810848e53000610159cca64f16cdb4f08c03b0bbdaa2",
            ),
        }],
    },
    IndexedCollection {
        name: "streamline-plump-color",
        releases: &[PinnedRelease {
            version: "1.2.2",
            sha256: Sha256Digest::from_hex(
                "1ec76fa9ca951d28f000e2d64b2ad56601969f945c14d23c8e0fe69c73225950",
            ),
        }],
    },
    IndexedCollection {
        name: "streamline-sharp",
        releases: &[PinnedRelease {
            version: "1.2.0",
            sha256: Sha256Digest::from_hex(
                "5115e4deb563c9dc18fac02c2f909ad2fd4eb352c526319c62df2b31facc22d0",
            ),
        }],
    },
    IndexedCollection {
        name: "streamline-sharp-color",
        releases: &[PinnedRelease {
            version: "1.2.2",
            sha256: Sha256Digest::from_hex(
                "8d72c27f8c33a1561e3126b1f7b553e3a89933c15083c24eee0c548a91246c3f",
            ),
        }],
    },
    IndexedCollection {
        name: "streamline-stickies-color",
        releases: &[PinnedRelease {
            version: "1.2.2",
            sha256: Sha256Digest::from_hex(
                "b222746987a039a683f36d5de39945536684b94f767c4a272b056bbd49380b50",
            ),
        }],
    },
    IndexedCollection {
        name: "streamline-ultimate",
        releases: &[PinnedRelease {
            version: "1.2.2",
            sha256: Sha256Digest::from_hex(
                "335dd06409dfeaf2b428ae2deaf419a9df2f99e1bf71063b52f62158aae54d1c",
            ),
        }],
    },
    IndexedCollection {
        name: "streamline-ultimate-color",
        releases: &[PinnedRelease {
            version: "1.2.2",
            sha256: Sha256Digest::from_hex(
                "cce247f44063ea88565e23fc016dd6a7fdcc12a49aeaff4b9d29829176f690e7",
            ),
        }],
    },
    IndexedCollection {
        name: "subway",
        releases: &[PinnedRelease {
            version: "1.2.0",
            sha256: Sha256Digest::from_hex(
                "e0ca640e588ccfe39deb194f8d760af98cc3da5b2e398551abc7b1730af7e613",
            ),
        }],
    },
    IndexedCollection {
        name: "svg-spinners",
        releases: &[PinnedRelease {
            version: "1.2.4",
            sha256: Sha256Digest::from_hex(
                "5cfcaf175ad81122de89cc84050c0f3ddb25bfdf2f0197ca628855aee7d5b9f7",
            ),
        }],
    },
    IndexedCollection {
        name: "system-uicons",
        releases: &[PinnedRelease {
            version: "1.2.4",
            sha256: Sha256Digest::from_hex(
                "016581ce298fe7f31e6093919e00a32e276da06585f4b61afd90595db17cd248",
            ),
        }],
    },
    IndexedCollection {
        name: "tabler",
        releases: &[PinnedRelease {
            version: "1.2.40",
            sha256: Sha256Digest::from_hex(
                "74cb008204f4e6263f714c949ab554e561deafac3d493f5765c604aa54c9cb9c",
            ),
        }],
    },
    IndexedCollection {
        name: "tdesign",
        releases: &[PinnedRelease {
            version: "1.2.19",
            sha256: Sha256Digest::from_hex(
                "8226e8ee7c0102b3e598e13401dfeccee32e81af486ebe8b2f90f4288ab8d2c9",
            ),
        }],
    },
    IndexedCollection {
        name: "teenyicons",
        releases: &[PinnedRelease {
            version: "1.2.2",
            sha256: Sha256Digest::from_hex(
                "2296f8f8e1b01ee982e1a3c276a4ed7bffaa09d01f49b4d9bc647991ef527c28",
            ),
        }],
    },
    IndexedCollection {
        name: "temaki",
        releases: &[PinnedRelease {
            version: "1.2.6",
            sha256: Sha256Digest::from_hex(
                "1900d5f749464659c6a5a9a0d6d5b39b3ce48205531e50516d2580553b36aaa2",
            ),
        }],
    },
    IndexedCollection {
        name: "thesvg",
        releases: &[PinnedRelease {
            version: "1.2.7",
            sha256: Sha256Digest::from_hex(
                "7f48efdd7d2e97e90d8c77436b8fa64ce850294a27199d73f56218d0ebfeb47e",
            ),
        }],
    },
    IndexedCollection {
        name: "thesvg-color",
        releases: &[PinnedRelease {
            version: "1.2.13",
            sha256: Sha256Digest::from_hex(
                "5751e59559f5c1bcbdc740863fe69c38b176a9d9ef84dbb25b43f31c95db6f9a",
            ),
        }],
    },
    IndexedCollection {
        name: "token",
        releases: &[PinnedRelease {
            version: "1.2.41",
            sha256: Sha256Digest::from_hex(
                "c2eb8b186649c569c90b5b1893ab28d4b068415c25c0a84e78b8e32b4dd00179",
            ),
        }],
    },
    IndexedCollection {
        name: "token-branded",
        releases: &[PinnedRelease {
            version: "1.2.45",
            sha256: Sha256Digest::from_hex(
                "c89afdfbbfe28d335adf588934343ff95412376e0c2a1be0753b2e0c4762a391",
            ),
        }],
    },
    IndexedCollection {
        name: "topcoat",
        releases: &[PinnedRelease {
            version: "1.2.0",
            sha256: Sha256Digest::from_hex(
                "3f29dd560f65b4c8e7c1866d5ea8d4d6aba5aa89aef09c5aeec6ec3a7545183e",
            ),
        }],
    },
    IndexedCollection {
        name: "twemoji",
        releases: &[PinnedRelease {
            version: "1.2.5",
            sha256: Sha256Digest::from_hex(
                "5d5d820790565b764f2728675d487c9ee4c1fc83916d8567d5aca8ba7527c242",
            ),
        }],
    },
    IndexedCollection {
        name: "typcn",
        releases: &[PinnedRelease {
            version: "1.2.2",
            sha256: Sha256Digest::from_hex(
                "17d9f32237702a39c07d07bcb8d3a6c9ac3f3a9dbb774e60082af1f3662858e1",
            ),
        }],
    },
    IndexedCollection {
        name: "uil",
        releases: &[PinnedRelease {
            version: "1.2.3",
            sha256: Sha256Digest::from_hex(
                "79d7a107db8fa76360de12615dbe7dbbd1029275facbb66566e341e223523f87",
            ),
        }],
    },
    IndexedCollection {
        name: "uim",
        releases: &[PinnedRelease {
            version: "1.2.3",
            sha256: Sha256Digest::from_hex(
                "68796942da6b05f65374d839240ed8a5e02891c14c87232126264a9be57cb5ec",
            ),
        }],
    },
    IndexedCollection {
        name: "uis",
        releases: &[PinnedRelease {
            version: "1.2.3",
            sha256: Sha256Digest::from_hex(
                "06fd62f266dbfeb8272f1c416fb3affc5f1d01d86fbaa8d55b7b9be4b72c728b",
            ),
        }],
    },
    IndexedCollection {
        name: "uit",
        releases: &[PinnedRelease {
            version: "1.2.3",
            sha256: Sha256Digest::from_hex(
                "cf3f5bca637d668ecc32c71d9352be8803ca6829eded7b5e822f1d9d98861f96",
            ),
        }],
    },
    IndexedCollection {
        name: "uiw",
        releases: &[PinnedRelease {
            version: "1.2.4",
            sha256: Sha256Digest::from_hex(
                "3436badb008550f5e148c05e02b1075681786a458aa5b1348032c8f0f7c8deff",
            ),
        }],
    },
    IndexedCollection {
        name: "unjs",
        releases: &[PinnedRelease {
            version: "1.2.4",
            sha256: Sha256Digest::from_hex(
                "66112969871befe4116adb410fba8703977895388dc942625398d84f10ba6357",
            ),
        }],
    },
    IndexedCollection {
        name: "vaadin",
        releases: &[PinnedRelease {
            version: "1.2.1",
            sha256: Sha256Digest::from_hex(
                "30a1164417f9a12853ca0fe79636a827863e2b29e4ca67b75f8c4e7a1c6f9dce",
            ),
        }],
    },
    IndexedCollection {
        name: "vadivam",
        releases: &[PinnedRelease {
            version: "1.2.1",
            sha256: Sha256Digest::from_hex(
                "dd64604d9d94df36ca5ace1bae53c32d27ca2a1c789a47ded19b385530a350b1",
            ),
        }],
    },
    IndexedCollection {
        name: "vs",
        releases: &[PinnedRelease {
            version: "1.2.0",
            sha256: Sha256Digest::from_hex(
                "c329a98e9dc4e2b8609e034d1a87ccd9531af45bdb07682187fbb213eee5f1a2",
            ),
        }],
    },
    IndexedCollection {
        name: "vscode-icons",
        releases: &[PinnedRelease {
            version: "1.2.81",
            sha256: Sha256Digest::from_hex(
                "65610db81723bbd7ed74b794d5ec8101ea5a36909e0300208a5f6c52943f39b8",
            ),
        }],
    },
    IndexedCollection {
        name: "websymbol",
        releases: &[PinnedRelease {
            version: "1.2.0",
            sha256: Sha256Digest::from_hex(
                "2dcc8379ca7821c2193570809a478dda5e5fdaa7a466864fe0e0de3d30e467cb",
            ),
        }],
    },
    IndexedCollection {
        name: "weui",
        releases: &[PinnedRelease {
            version: "1.2.4",
            sha256: Sha256Digest::from_hex(
                "f9e04662d469008f8b9c28fbb226e1ba7de989c7bde4e148f6c6027298c55903",
            ),
        }],
    },
    IndexedCollection {
        name: "whh",
        releases: &[PinnedRelease {
            version: "1.2.0",
            sha256: Sha256Digest::from_hex(
                "e5e26a3ba797e630d1db0c5131149c9d120f8184fd87d295612db3e117f0b6a1",
            ),
        }],
    },
    IndexedCollection {
        name: "wi",
        releases: &[PinnedRelease {
            version: "1.2.1",
            sha256: Sha256Digest::from_hex(
                "6e1834d42807c4c72992f1506e933e296de26c493a8506211500f7c1fe15b07e",
            ),
        }],
    },
    IndexedCollection {
        name: "wordpress",
        releases: &[PinnedRelease {
            version: "1.2.23",
            sha256: Sha256Digest::from_hex(
                "f11b020bec01e2c12076b0ba3d517eb6d0d7c7e15ae0d294373a65ce5d38e488",
            ),
        }],
    },
    IndexedCollection {
        name: "wpf",
        releases: &[PinnedRelease {
            version: "1.2.0",
            sha256: Sha256Digest::from_hex(
                "f8ff162d1d2e3ecdb0135b112ccfaf448d53acfeeedb57ba4b77cd9496a43f8d",
            ),
        }],
    },
    IndexedCollection {
        name: "zmdi",
        releases: &[PinnedRelease {
            version: "1.2.0",
            sha256: Sha256Digest::from_hex(
                "7b8c6edb191b7684ce775e5d6997327c7d46c8475eeb30088024a4b76356293d",
            ),
        }],
    },
    IndexedCollection {
        name: "zondicons",
        releases: &[PinnedRelease {
            version: "1.2.2",
            sha256: Sha256Digest::from_hex(
                "ad53156d4aa7dd0b81a9bb052645d2c832283ad2dcc06d40b68e6a648176c954",
            ),
        }],
    },
];
