//! Replacing Typst's own sentence where it cannot name what the site author must do: a file
//! this boundary refuses to read, an import from a Tola package that did not resolve, and a check
//! that resolved no world.

use std::path::Path;

use tola_build::diagnostic::{Diagnostic, DiagnosticCode, Location};

use super::projection::diagnostic_path;

/// The code a file this boundary refuses arrives under.
///
/// It is the one producer that names the refused file as the diagnostic's location: the world's own
/// failures (`typst.world`) hold no location and already write their own sentence and help, and a
/// page that imports a refused file is reported where the import is written.
const REFUSAL_CODE: DiagnosticCode = tola_build::codes::typst::SNAPSHOT;

/// What each refusal costs the page that reads the file.
const REFUSED_GENERATED: &str = "is generated by Tola, so the page that reads it cannot be checked";
const REFUSED_OUTSIDE: &str = "is outside the site, so the page that reads it cannot be checked";

/// What the author does about each refusal.
const REFUSED_GENERATED_HELP: &str =
    "point the import at the input it is generated from, or edit that input";
const REFUSED_OUTSIDE_HELP: &str = "move the file below the site root, or copy it in";

/// Replace Typst's own sentence for a file this boundary refuses with what the refusal costs
/// the author, keeping the sentence Typst wrote.
///
/// A refused read arrives as one access error, so its sentence names a file and no reason. The
/// boundary answers with the exact reason when it is asked again about the path the diagnostic
/// itself names, which is what turns "Tola is not allowed to read it" into a step the author
/// takes. A path the boundary accepts keeps the sentence its producer wrote.
pub(super) fn refine_refused_source(diagnostic: &mut Diagnostic, root: &Path) {
    if diagnostic.code != REFUSAL_CODE {
        return;
    }
    let Some(location) = &diagnostic.location else {
        return;
    };
    let Some(path) = diagnostic_path(root, location) else {
        return;
    };
    let Ok(Some(refusal)) = crate::sources::base_source_boundary(root, true).refusal(&path) else {
        return;
    };
    let (reason, help) = match refusal {
        tola_typst::SourceRefusal::GeneratedState => (REFUSED_GENERATED, REFUSED_GENERATED_HELP),
        tola_typst::SourceRefusal::OutsideSite => (REFUSED_OUTSIDE, REFUSED_OUTSIDE_HELP),
    };
    let typst_sentence = std::mem::replace(
        &mut diagnostic.message,
        format!("`{}` {reason}", location.path),
    );
    diagnostic.notes.push(typst_sentence);
    diagnostic.help.push(tola_build::diagnostic::Help {
        message: help.to_owned(),
        location: None,
    });
}

/// Typst's sentence for an import whose module has no such name.
const UNRESOLVED_IMPORT: &str = "unresolved import";

/// What the author does about an import from a Tola package that did not resolve.
const UNRESOLVED_IMPORT_HELP: &str = "run `tola build` to install the site's packages, or rerun `tola editor setup` to refresh the editor's package copies";

/// Replace Typst's own sentence for an import from a Tola package that named nothing with
/// what the site author can act on.
///
/// Typst writes only `unresolved import`, and locates the failure inside the package's own file
/// when the package could not be resolved, with a `while importing` chain back to the site. The
/// author can change neither: the record answers at the outermost site file the chain names, or
/// at the site import line itself, and Typst's sentence and chain stay in the debug log.
pub(super) fn refine_unresolved_import(diagnostic: &mut Diagnostic) {
    if diagnostic.message != UNRESOLVED_IMPORT {
        return;
    }
    let Some(location) = diagnostic.location.as_ref() else {
        return;
    };
    let inside_package = location.path.starts_with('@');
    let (package, name) = if inside_package {
        (tola_package_identity(&location.path), None)
    } else {
        (
            excerpted_line(location).and_then(|line| tola_package_identity(&line.text)),
            highlighted_name(location),
        )
    };
    let Some(package) = package.map(str::to_owned) else {
        return;
    };
    let name = name.map(str::to_owned);
    tracing::debug!(
        package = %package,
        message = %diagnostic.message,
        location = ?diagnostic.location.as_ref().map(|location| format!(
            "{}:{}",
            location.path,
            location.line.unwrap_or(1),
        )),
        trace = ?diagnostic
            .trace
            .iter()
            .map(|frame| frame.message.as_str())
            .collect::<Vec<_>>(),
        "an unresolved Tola package import reached the editor",
    );
    // A failure inside a package answers where the author can act: the import the chain reaches
    // from the site. A chain that names no site file keeps the package location it had.
    if inside_package
        && let Some(site) = diagnostic.trace.iter().rev().find_map(|frame| {
            let location = frame.location.as_ref()?;
            (!location.path.starts_with('@')).then(|| location.clone())
        })
    {
        diagnostic.location = Some(site);
    }
    diagnostic.trace.clear();
    diagnostic.message = match name {
        Some(name) => {
            format!("Tola could not resolve the name `{name}` this import reads from `{package}`")
        }
        None if inside_package => format!("Tola could not resolve the package `{package}`"),
        None => format!("Tola could not resolve this import from `{package}`"),
    };
    diagnostic.code = crate::codes::editor::UNRESOLVED_PACKAGE_IMPORT;
    diagnostic.help.push(tola_build::diagnostic::Help {
        message: UNRESOLVED_IMPORT_HELP.to_owned(),
        location: None,
    });
}

/// What a check that resolved no world says, in the words the author acts on.
const UNREAD_CONFIGURATION: &str = "Tola could not read the site's configuration";

/// What the unread configuration costs the answers the author waits on.
const UNREAD_CONFIGURATION_NOTE: &str = "pages, labels, and hovers stay unavailable until it loads";

/// What the author does about a configuration Tola could not read.
const UNREAD_CONFIGURATION_HELP: &str = "fix the problem reported in `tola.toml`";

/// Replace Typst's own sentence with what a configuration Tola could not read costs the author,
/// keeping the reason Typst wrote.
///
/// Only the configuration's own fallback diagnostic is refined: one that has a precise
/// location and a sentence written for it is already the sentence the author acts on.
pub(crate) fn refine_unread_configuration(diagnostics: &mut [Diagnostic]) {
    for diagnostic in diagnostics {
        if diagnostic.code != crate::codes::editor::CONFIGURATION {
            continue;
        }
        let reason = std::mem::replace(&mut diagnostic.message, UNREAD_CONFIGURATION.to_owned());
        diagnostic.notes.push(reason);
        diagnostic.notes.push(UNREAD_CONFIGURATION_NOTE.to_owned());
        diagnostic.help.push(tola_build::diagnostic::Help {
            message: UNREAD_CONFIGURATION_HELP.to_owned(),
            location: None,
        });
    }
}

/// The `@tola/…` package identity `text` names, when it names one.
///
/// `text` is a package location path, a trace sentence, or a line of source. The identity ends at
/// the package's version; a path inside the package or a list of imported names continues after.
fn tola_package_identity(text: &str) -> Option<&str> {
    const NAMESPACE: &str = "@tola/";
    let start = text.find(NAMESPACE)?;
    let (name, after_name) = text[start + NAMESPACE.len()..].split_once(':')?;
    let version = after_name
        .find(|character: char| !character.is_ascii_digit() && character != '.')
        .unwrap_or(after_name.len());
    (version > 0 && !name.is_empty())
        .then(|| &text[start..start + NAMESPACE.len() + name.len() + 1 + version])
}

/// The source line the location points at, or the first line it has.
fn excerpted_line(location: &Location) -> Option<&tola_build::diagnostic::SourceLine> {
    location
        .source_lines
        .iter()
        .find(|line| Some(line.line) == location.line)
        .or_else(|| location.source_lines.first())
}

/// The name Typst's own highlight covers: the component the import could not find.
fn highlighted_name(location: &Location) -> Option<&str> {
    let line = excerpted_line(location)?;
    let (start, end) = line.highlight?;
    let name = line.text.get(start..end)?.trim();
    (!name.is_empty() && !name.contains(char::is_whitespace)).then_some(name)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::diagnostic::tests::Site;
    use lsp_types::{NumberOrString, Position, Range};
    use tola_build::diagnostic::{Diagnostic, Severity};

    /// A location a producer named without its text.
    fn located_at(path: &str, line: usize, column: usize) -> Location {
        Location {
            path: path.into(),
            line: Some(line),
            column: Some(column),
            range: None,
            source_lines: Vec::new(),
        }
    }

    /// A snapshot read failure is worded by where the path it names sits.
    #[test]
    fn snapshot_failure_message_follows_the_path() {
        for (path, reason, expected) in [
            (
                "../outside.typ",
                "cannot read file outside of project root",
                "`../outside.typ` is outside the site, so the page that reads it cannot be checked\
                 \nnote: cannot read file outside of project root\
                 \nhelp: move the file below the site root, or copy it in",
            ),
            (
                ".tola/generated.typ",
                "cannot read file: access denied",
                "`.tola/generated.typ` is generated by Tola, so the page that reads it cannot be checked\
                 \nnote: cannot read file: access denied\
                 \nhelp: point the import at the input it is generated from, or edit that input",
            ),
            (
                "content/index.typ",
                "cannot read file: access denied",
                "cannot read file: access denied",
            ),
        ] {
            let mut site = Site::new(&[]);
            site.publish(vec![Diagnostic::at_path(
                tola_build::codes::typst::SNAPSHOT,
                Severity::Error,
                path,
                reason,
            )]);
            let diagnostics = site.diagnostics();
            let [diagnostic] = diagnostics.as_slice() else {
                panic!("one diagnostic: {diagnostics:?}");
            };
            assert_eq!(diagnostic.message, expected, "{path}");
        }
    }

    /// Typst's sentence for an import written in the site, with the package and name it
    /// reads: the name is what `@tola/schema:0.0.0` does not export.
    #[test]
    fn unresolved_site_import_names_its_package() {
        let mut site = Site::new(&[("content/post.typ", "#import \"@tola/schema:0.0.0\": nope\n")]);
        site.publish(vec![
            Diagnostic::at_path(
                tola_build::codes::typst::COMPILE,
                Severity::Error,
                "content/post.typ",
                "unresolved import",
            )
            .with_source_excerpt(
                1,
                31,
                "#import \"@tola/schema:0.0.0\": nope",
                Some((30, 34)),
            ),
        ]);
        let pushed = site.pushed();
        let reported: Vec<_> = pushed
            .iter()
            .filter(|(_, diagnostics)| !diagnostics.is_empty())
            .collect();
        let [(uri, diagnostics)] = reported.as_slice() else {
            panic!("one document has the import: {pushed:?}");
        };
        assert!(uri.ends_with("content/post.typ"), "{uri}");
        let [diagnostic] = diagnostics.as_slice() else {
            panic!("one diagnostic: {diagnostics:?}");
        };
        assert_eq!(
            diagnostic.code,
            Some(NumberOrString::String(
                "editor.unresolved_package_import".into()
            ))
        );
        assert_eq!(
            diagnostic.message.lines().next(),
            Some(
                "Tola could not resolve the name `nope` this import reads from `@tola/schema:0.0.0`"
            )
        );
        assert!(
            diagnostic.message.contains(UNRESOLVED_IMPORT_HELP),
            "{diagnostic:?}"
        );
        assert_eq!(
            diagnostic.range,
            Range::new(Position::new(0, 30), Position::new(0, 34))
        );
    }

    /// A package that could not be read is reported at the site import that reaches it, with the
    /// chain's own text kept out of the message.
    #[test]
    fn package_failure_follows_the_site_import() {
        let mut site = Site::new(&[(
            "content/about.typ",
            "#import \"@tola/source:0.0.0\": all-sources\n",
        )]);
        let mut diagnostic = Diagnostic::at_path(
            tola_build::codes::typst::COMPILE,
            Severity::Error,
            "@tola/schema:0.0.0/lib.typ",
            "unresolved import",
        )
        .with_position(18, 8);
        diagnostic.trace.push(tola_build::diagnostic::TraceFrame {
            message: "while importing `@tola/schema:0.0.0`".into(),
            location: Some(located_at("@tola/source:0.0.0/lib.typ", 54, 3)),
        });
        diagnostic.trace.push(tola_build::diagnostic::TraceFrame {
            message: "while importing `@tola/source:0.0.0`".into(),
            location: Some(located_at("content/about.typ", 1, 2)),
        });
        site.publish(vec![diagnostic]);
        let pushed = site.pushed();
        let reported: Vec<_> = pushed
            .iter()
            .filter(|(_, diagnostics)| !diagnostics.is_empty())
            .collect();
        let [(uri, diagnostics)] = reported.as_slice() else {
            panic!("one document has the chain's site end: {pushed:?}");
        };
        assert!(uri.ends_with("content/about.typ"), "{uri}");
        let [diagnostic] = diagnostics.as_slice() else {
            panic!("one diagnostic: {diagnostics:?}");
        };
        assert_eq!(
            diagnostic.code,
            Some(NumberOrString::String(
                "editor.unresolved_package_import".into()
            ))
        );
        assert_eq!(
            diagnostic.message.lines().next(),
            Some("Tola could not resolve the package `@tola/schema:0.0.0`")
        );
        assert!(
            diagnostic.message.contains(UNRESOLVED_IMPORT_HELP),
            "{diagnostic:?}"
        );
        assert_eq!(
            diagnostic.range,
            Range::new(Position::new(0, 1), Position::new(0, 1))
        );
        for raw in [
            "unresolved import",
            "while importing",
            "@tola/schema:0.0.0/lib.typ",
            "@tola/source:0.0.0/lib.typ",
        ] {
            assert!(
                !diagnostic.message.contains(raw),
                "raw text reached the message: {raw}"
            );
        }
    }

    /// Every other Typst sentence reaches the editor as Typst wrote it.
    #[test]
    fn unrelated_typst_sentences_are_unchanged() {
        for message in ["unknown variable: undefined_name", "loop does not converge"] {
            let mut site = Site::new(&[("content/post.typ", "= Title\n#undefined_name\n")]);
            site.publish(vec![
                Diagnostic::at_path(
                    tola_build::codes::typst::COMPILE,
                    Severity::Error,
                    "content/post.typ",
                    message,
                )
                .with_position(2, 1),
            ]);
            let diagnostics = site.diagnostics();
            let [diagnostic] = diagnostics.as_slice() else {
                panic!("one diagnostic for {message}");
            };
            assert_eq!(diagnostic.message, message);
            assert_eq!(
                diagnostic.code,
                Some(NumberOrString::String("typst.compile".into()))
            );
        }
    }
}
