//! Atomic CSS build stage.

use std::fs;
use std::path::{Path, PathBuf};

use anyhow::{Context, Result, anyhow, bail};

use crate::config::SiteConfig;
use crate::css::config::AtomicCssFile;

const GENERATED_MARKER: &str =
    "/* Generated by Tola Atomic CSS. Do not edit this file directly. */\n";

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct AtomicCssOutput {
    pub path: PathBuf,
    pub url: String,
    pub written: bool,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct AtomicCssAsset {
    pub path: PathBuf,
    pub url: String,
}

/// Build configured Atomic CSS output.
pub fn build(config: &SiteConfig) -> Result<Option<AtomicCssOutput>> {
    let css = &config.build.atomic_css;
    if !css.enable {
        return Ok(None);
    }

    let asset =
        output_asset(config).ok_or_else(|| anyhow!("atomic CSS output is not configured"))?;
    ensure_output_is_available(config, &asset)?;
    let sheet = load_sheet_config(config)?;
    let source_texts = collect_sources(&css.sources)?;
    let source_refs = source_texts.iter().map(String::as_str);
    let rendered = mark_generated(&crate::css::compiler::compile(source_refs, &sheet)?);
    let written = write_if_changed(&asset.path, &rendered)?;
    if written {
        crate::asset::version::update_version(&asset.path);
    }

    Ok(Some(AtomicCssOutput {
        path: asset.path,
        url: asset.url,
        written,
    }))
}

/// Resolve the configured Atomic CSS output asset.
pub fn output_asset(config: &SiteConfig) -> Option<AtomicCssAsset> {
    if !config.build.atomic_css.enable {
        return None;
    }

    let output_rel = config.build.atomic_css.output.as_ref()?;
    Some(AtomicCssAsset {
        path: output_rel.output_path(config.paths()),
        url: output_rel.href(config.paths()),
    })
}

fn load_sheet_config(config: &SiteConfig) -> Result<AtomicCssFile> {
    match &config.build.atomic_css.config {
        Some(path) => AtomicCssFile::parse_path(path).map_err(Into::into),
        None => Ok(AtomicCssFile::default()),
    }
}

fn collect_sources(paths: &[PathBuf]) -> Result<Vec<String>> {
    let mut files = Vec::new();
    for path in paths {
        collect_path(path, &mut files)?;
    }
    files.sort();

    files
        .into_iter()
        .map(|path| {
            let bytes = fs::read(&path).with_context(|| {
                format!("failed to read Atomic CSS source '{}'", path.display())
            })?;
            Ok(String::from_utf8_lossy(&bytes).into_owned())
        })
        .collect()
}

fn collect_path(path: &Path, files: &mut Vec<PathBuf>) -> Result<()> {
    if path.is_file() {
        files.push(path.to_path_buf());
        return Ok(());
    }
    if !path.is_dir() {
        return Err(anyhow!(
            "Atomic CSS source '{}' is not a file or directory",
            path.display()
        ));
    }

    for entry in fs::read_dir(path)
        .with_context(|| format!("failed to read Atomic CSS source dir '{}'", path.display()))?
    {
        let entry = entry?;
        collect_path(&entry.path(), files)?;
    }
    Ok(())
}

fn write_if_changed(path: &Path, content: &str) -> Result<bool> {
    if path.exists() {
        let existing = fs::read_to_string(path)?;
        if existing == content {
            return Ok(false);
        }
        if !is_owned_output(&existing) {
            bail!(
                "refusing to overwrite '{}': Atomic CSS output path already exists and is not owned by Tola Atomic CSS",
                path.display()
            );
        }
    }
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)?;
    }
    fs::write(path, content)?;
    Ok(true)
}

fn ensure_output_is_available(config: &SiteConfig, asset: &AtomicCssAsset) -> Result<()> {
    if asset.path.extension().and_then(|ext| ext.to_str()) != Some("css") {
        bail!(
            "Atomic CSS output '{}' must use the .css extension",
            asset.url
        );
    }

    ensure_output_is_not_source(config, asset)?;

    let output = crate::utils::path::normalize_path(&asset.path);
    for route in crate::asset::scan_global_assets(config)
        .into_iter()
        .chain(crate::asset::scan_flatten_assets(config))
        .chain(crate::asset::scan_content_assets(config))
    {
        if crate::utils::path::normalize_path(&route.output) == output {
            bail!(
                "Atomic CSS output '{}' conflicts with configured asset '{}'",
                asset.url,
                route.source.display()
            );
        }
    }
    Ok(())
}

fn ensure_output_is_not_source(config: &SiteConfig, asset: &AtomicCssAsset) -> Result<()> {
    let output = crate::utils::path::normalize_path(&asset.path);

    if path_is_inside(&output, &config.build.content) {
        bail!(
            "Atomic CSS output '{}' is inside content source '{}'",
            asset.url,
            config.build.content.display()
        );
    }

    for source in &config.build.deps {
        if path_is_inside(&output, source) {
            bail!(
                "Atomic CSS output '{}' is inside dependency source '{}'",
                asset.url,
                source.display()
            );
        }
    }

    for source in config.build.assets.nested_sources() {
        if path_is_inside(&output, source) {
            bail!(
                "Atomic CSS output '{}' is inside configured asset source '{}'",
                asset.url,
                source.display()
            );
        }
    }

    for source in config.build.assets.flatten_sources() {
        if paths_equal(&output, source) {
            bail!(
                "Atomic CSS output '{}' conflicts with configured flatten asset '{}'",
                asset.url,
                source.display()
            );
        }
    }

    for source in &config.build.atomic_css.sources {
        if path_is_inside(&output, source) {
            bail!(
                "Atomic CSS output '{}' is inside Atomic CSS source '{}'",
                asset.url,
                source.display()
            );
        }
    }

    Ok(())
}

fn path_is_inside(path: &Path, source: &Path) -> bool {
    let path = crate::utils::path::normalize_existing_prefix(path);
    let source = crate::utils::path::normalize_existing_prefix(source);
    path == source || path.starts_with(source)
}

fn paths_equal(left: &Path, right: &Path) -> bool {
    crate::utils::path::normalize_existing_prefix(left)
        == crate::utils::path::normalize_existing_prefix(right)
}

fn mark_generated(css: &str) -> String {
    if css.starts_with(GENERATED_MARKER) {
        css.to_string()
    } else {
        format!("{GENERATED_MARKER}{css}")
    }
}

fn is_owned_output(css: &str) -> bool {
    css.starts_with(GENERATED_MARKER)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::SiteConfig;
    use std::fs;
    use tempfile::TempDir;

    #[test]
    fn build_writes_generated_css_from_configured_sources() {
        let temp = TempDir::new().unwrap();
        let root = temp.path();
        let content = root.join("content");
        let output = root.join("public");
        fs::create_dir_all(&content).unwrap();
        fs::write(content.join("index.html"), r#"<div class="flex"></div>"#).unwrap();

        let mut config = SiteConfig::default();
        config.set_root(root);
        config.build.output = output;
        config.build.atomic_css.enable = true;
        config.build.atomic_css.output = Some("assets/site.css".into());
        config.build.atomic_css.sources = vec![content];

        let result = build(&config).unwrap().unwrap();

        assert!(result.written);
        assert_eq!(
            result.path,
            config.paths().output_dir().join("assets/site.css")
        );
        let css = fs::read_to_string(result.path).unwrap();
        assert!(css.contains(".flex"));
    }

    #[test]
    fn build_refreshes_output_version_after_rewrite() {
        crate::asset::version::clear();

        let temp = TempDir::new().unwrap();
        let root = temp.path();
        let content = root.join("content");
        let output = root.join("public");
        let page = content.join("index.html");
        fs::create_dir_all(&content).unwrap();
        fs::write(&page, r#"<div class="flex"></div>"#).unwrap();

        let mut config = SiteConfig::default();
        config.set_root(root);
        config.build.output = output;
        config.build.atomic_css.enable = true;
        config.build.atomic_css.output = Some("assets/site.css".into());
        config.build.atomic_css.sources = vec![content];

        let first = build(&config).unwrap().unwrap();
        let first_href = crate::asset::version::versioned_url(&first.url, &first.path);

        fs::write(&page, r#"<div class="grid"></div>"#).unwrap();
        let second = build(&config).unwrap().unwrap();
        let second_href = crate::asset::version::versioned_url(&second.url, &second.path);

        assert!(second.written);
        assert_ne!(first_href, second_href);

        crate::asset::version::clear();
    }

    #[test]
    fn build_can_update_owned_output_under_asset_url_namespace() {
        let temp = TempDir::new().unwrap();
        let root = temp.path();
        let assets = root.join("assets");
        let content = root.join("content");
        let output = root.join("public");
        let page = content.join("index.html");
        fs::create_dir_all(&assets).unwrap();
        fs::create_dir_all(&content).unwrap();
        fs::write(&page, r#"<div class="flex"></div>"#).unwrap();

        let mut config = SiteConfig::default();
        config.set_root(root);
        config.build.assets.normalize(root);
        config.build.output = output;
        config.build.atomic_css.enable = true;
        config.build.atomic_css.output = Some("assets/site.css".into());
        config.build.atomic_css.sources = vec![content];

        let first = build(&config).unwrap().unwrap();
        fs::write(&page, r#"<div class="grid"></div>"#).unwrap();
        let second = build(&config).unwrap().unwrap();

        assert!(first.written);
        assert!(second.written);
        assert_eq!(
            second.path,
            config.paths().output_dir().join("assets/site.css")
        );
        let css = fs::read_to_string(second.path).unwrap();
        assert!(css.contains("Generated by Tola Atomic CSS"));
        assert!(css.contains(".grid"));
    }

    #[test]
    fn build_refuses_output_inside_configured_asset_source() {
        let temp = TempDir::new().unwrap();
        let root = temp.path();
        let assets = root.join("assets");
        let content = root.join("content");
        fs::create_dir_all(&assets).unwrap();
        fs::create_dir_all(&content).unwrap();
        fs::write(content.join("index.html"), r#"<div class="flex"></div>"#).unwrap();

        let mut config = SiteConfig::default();
        config.set_root(root);
        config.build.assets.normalize(root);
        config.build.output = root.to_path_buf();
        config.build.atomic_css.enable = true;
        config.build.atomic_css.output = Some("assets/site.css".into());
        config.build.atomic_css.sources = vec![content];

        let err = build(&config).unwrap_err();

        assert!(err.to_string().contains("inside configured asset source"));
        assert!(!assets.join("site.css").exists());
    }

    #[test]
    fn build_refuses_to_overwrite_unowned_existing_output() {
        let temp = TempDir::new().unwrap();
        let root = temp.path();
        let content = root.join("content");
        let output = root.join("public");
        let output_css = output.join("assets/site.css");
        fs::create_dir_all(&content).unwrap();
        fs::create_dir_all(output_css.parent().unwrap()).unwrap();
        fs::write(content.join("index.html"), r#"<div class="flex"></div>"#).unwrap();
        fs::write(&output_css, "user css").unwrap();

        let mut config = SiteConfig::default();
        config.set_root(root);
        config.build.output = output;
        config.build.atomic_css.enable = true;
        config.build.atomic_css.output = Some("assets/site.css".into());
        config.build.atomic_css.sources = vec![content];

        let err = build(&config).unwrap_err();

        assert!(err.to_string().contains("refusing to overwrite"));
        assert_eq!(fs::read_to_string(output_css).unwrap(), "user css");
    }

    #[test]
    fn build_errors_when_output_conflicts_with_configured_asset() {
        let temp = TempDir::new().unwrap();
        let root = temp.path();
        let content = root.join("content");
        let assets = root.join("assets");
        let output = root.join("public");
        fs::create_dir_all(&content).unwrap();
        fs::create_dir_all(&assets).unwrap();
        fs::write(content.join("index.html"), r#"<div class="flex"></div>"#).unwrap();
        fs::write(assets.join("site.css"), "asset css").unwrap();

        let mut config = SiteConfig::default();
        config.set_root(root);
        config.build.output = output.clone();
        config.build.assets.nested =
            vec![crate::config::section::build::assets::NestedEntry::Simple(
                assets,
            )];
        config.build.atomic_css.enable = true;
        config.build.atomic_css.output = Some("assets/site.css".into());
        config.build.atomic_css.sources = vec![content];

        let err = build(&config).unwrap_err();

        assert!(err.to_string().contains("conflicts with configured asset"));
        assert!(!output.join("assets/site.css").exists());
    }
}
