//! Atomic CSS build stage.

use std::fs;
use std::path::{Path, PathBuf};

use anyhow::{Result, bail};

use crate::config::SiteConfig;
use crate::config::section::build::AtomicCssConfig;
use crate::css::config::AtomicCssFile;

const GENERATED_MARKER: &str =
    "/* Generated by Tola Atomic CSS. Do not edit this file directly. */\n";

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct AtomicCssOutput {
    pub path: PathBuf,
    pub url: String,
    pub written: bool,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct AtomicCssAsset {
    pub path: PathBuf,
    pub url: String,
}

/// Build configured Atomic CSS output.
pub fn build(config: &SiteConfig) -> Result<Option<AtomicCssOutput>> {
    let css = &config.build.atomic_css;
    if !css.enable {
        return Ok(None);
    }

    let asset = output_asset(config).expect("atomic CSS asset exists when enabled");
    ensure_output_is_available(config, &asset)?;
    let sheet = load_sheet_config(config)?;
    let source_texts = crate::css::source::texts(config)?;
    let source_refs = source_texts.iter().map(String::as_str);
    let rendered = mark_generated(&crate::css::compiler::compile(source_refs, &sheet)?);
    let written = write_if_changed(&asset.path, &rendered)?;
    if written {
        crate::asset::version::update_version(&asset.path);
    }

    Ok(Some(AtomicCssOutput {
        path: asset.path,
        url: asset.url,
        written,
    }))
}

/// Resolve the fixed Atomic CSS output asset.
pub fn output_asset(config: &SiteConfig) -> Option<AtomicCssAsset> {
    if !config.build.atomic_css.enable {
        return None;
    }

    Some(AtomicCssAsset {
        path: AtomicCssConfig::output_path(config.paths()),
        url: AtomicCssConfig::output_href(config.paths()),
    })
}

fn load_sheet_config(config: &SiteConfig) -> Result<AtomicCssFile> {
    match &config.build.atomic_css.config {
        Some(path) => AtomicCssFile::parse_path(path).map_err(Into::into),
        None => Ok(AtomicCssFile::default()),
    }
}

fn write_if_changed(path: &Path, content: &str) -> Result<bool> {
    if path.exists() {
        let existing = fs::read_to_string(path)?;
        if existing == content {
            return Ok(false);
        }
        if !is_owned_output(&existing) {
            bail!(
                "refusing to overwrite '{}': Atomic CSS output path already exists and is not owned by Tola Atomic CSS",
                path.display()
            );
        }
    }
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)?;
    }
    fs::write(path, content)?;
    Ok(true)
}

fn ensure_output_is_available(config: &SiteConfig, asset: &AtomicCssAsset) -> Result<()> {
    if asset.path.extension().and_then(|ext| ext.to_str()) != Some("css") {
        bail!(
            "Atomic CSS output '{}' must use the .css extension",
            asset.url
        );
    }

    ensure_output_is_not_source(config, asset)?;

    let output = crate::utils::path::normalize_path(&asset.path);
    for route in crate::asset::scan_nested_assets(config)
        .into_iter()
        .chain(crate::asset::scan_flatten_assets(config))
        .chain(crate::asset::scan_content_assets(config))
    {
        if crate::utils::path::normalize_path(&route.output) == output {
            bail!(
                "Atomic CSS output '{}' conflicts with configured asset '{}'",
                asset.url,
                route.source.display()
            );
        }
    }
    Ok(())
}

fn ensure_output_is_not_source(config: &SiteConfig, asset: &AtomicCssAsset) -> Result<()> {
    let output = crate::utils::path::normalize_path(&asset.path);

    if path_is_inside(&output, &config.build.content) {
        bail!(
            "Atomic CSS output '{}' is inside content source '{}'",
            asset.url,
            config.build.content.display()
        );
    }

    for source in &config.build.deps {
        if path_is_inside(&output, source) {
            bail!(
                "Atomic CSS output '{}' is inside dependency source '{}'",
                asset.url,
                source.display()
            );
        }
    }

    for source in config.build.assets.nested_sources() {
        if path_is_inside(&output, source) {
            bail!(
                "Atomic CSS output '{}' is inside configured asset source '{}'",
                asset.url,
                source.display()
            );
        }
    }

    for source in config.build.assets.flatten_sources() {
        if paths_equal(&output, source) {
            bail!(
                "Atomic CSS output '{}' conflicts with configured file asset '{}'",
                asset.url,
                source.display()
            );
        }
    }

    if let Some(entries) = &config.build.atomic_css.source {
        for entry in entries {
            if path_is_inside(&output, entry) {
                bail!(
                    "Atomic CSS output '{}' is inside Atomic CSS source '{}'",
                    asset.url,
                    entry.display()
                );
            }
        }
    }

    Ok(())
}

fn path_is_inside(path: &Path, source: &Path) -> bool {
    let path = crate::utils::path::normalize_existing_prefix(path);
    let source = crate::utils::path::normalize_existing_prefix(source);
    path == source || path.starts_with(source)
}

fn paths_equal(left: &Path, right: &Path) -> bool {
    crate::utils::path::normalize_existing_prefix(left)
        == crate::utils::path::normalize_existing_prefix(right)
}

fn mark_generated(css: &str) -> String {
    if css.starts_with(GENERATED_MARKER) {
        css.to_string()
    } else {
        format!("{GENERATED_MARKER}{css}")
    }
}

fn is_owned_output(css: &str) -> bool {
    css.starts_with(GENERATED_MARKER)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::SiteConfig;
    use std::fs;
    use tempfile::TempDir;

    #[test]
    fn build_writes_generated_css_from_default_source_scan() {
        let temp = TempDir::new().unwrap();
        let root = temp.path();
        let content = root.join("content");
        let output = root.join("public");
        fs::create_dir_all(&content).unwrap();
        fs::write(content.join("index.html"), r#"<div class="flex"></div>"#).unwrap();

        let mut config = SiteConfig::default();
        config.set_root(root);
        config.build.output = output;
        config.build.atomic_css.enable = true;

        let result = build(&config).unwrap().unwrap();

        assert!(result.written);
        assert_eq!(
            result.path,
            config.paths().output_dir().join(".tola/atomic.css")
        );
        let css = fs::read_to_string(result.path).unwrap();
        assert!(css.contains(".flex"));
    }

    #[test]
    fn build_uses_explicit_source_without_auto_scan() {
        let temp = TempDir::new().unwrap();
        let root = temp.path();
        let content = root.join("content");
        let components = root.join("components");
        let output = root.join("public");
        fs::create_dir_all(&content).unwrap();
        fs::create_dir_all(&components).unwrap();
        fs::write(content.join("index.html"), r#"<div class="flex"></div>"#).unwrap();
        fs::write(
            components.join("button.html"),
            r#"<button class="grid"></button>"#,
        )
        .unwrap();

        let mut config = crate::config::test_parse_config(
            r#"
[build.atomic_css]
enable = true
source = ["components/button.html"]
"#,
        );
        config.set_root(root);
        config.build.output = output;
        config.build.atomic_css.normalize(root);

        let result = build(&config).unwrap().unwrap();
        let css = fs::read_to_string(result.path).unwrap();

        assert!(css.contains(".grid"));
        assert!(!css.contains(".flex"));
    }

    #[test]
    fn build_refreshes_output_version_after_rewrite() {
        crate::asset::version::clear();

        let temp = TempDir::new().unwrap();
        let root = temp.path();
        let content = root.join("content");
        let output = root.join("public");
        let page = content.join("index.html");
        fs::create_dir_all(&content).unwrap();
        fs::write(&page, r#"<div class="flex"></div>"#).unwrap();

        let mut config = SiteConfig::default();
        config.set_root(root);
        config.build.output = output;
        config.build.atomic_css.enable = true;

        let first = build(&config).unwrap().unwrap();
        let first_href = crate::asset::version::versioned_url(&first.url, &first.path);

        fs::write(&page, r#"<div class="grid"></div>"#).unwrap();
        let second = build(&config).unwrap().unwrap();
        let second_href = crate::asset::version::versioned_url(&second.url, &second.path);

        assert!(second.written);
        assert_ne!(first_href, second_href);

        crate::asset::version::clear();
    }

    #[test]
    fn build_can_update_owned_output() {
        let temp = TempDir::new().unwrap();
        let root = temp.path();
        let content = root.join("content");
        let output = root.join("public");
        let page = content.join("index.html");
        fs::create_dir_all(&content).unwrap();
        fs::write(&page, r#"<div class="flex"></div>"#).unwrap();

        let mut config = SiteConfig::default();
        config.set_root(root);
        config.build.assets.normalize(root);
        config.build.output = output;
        config.build.atomic_css.enable = true;

        let first = build(&config).unwrap().unwrap();
        fs::write(&page, r#"<div class="grid"></div>"#).unwrap();
        let second = build(&config).unwrap().unwrap();

        assert!(first.written);
        assert!(second.written);
        assert_eq!(
            second.path,
            config.paths().output_dir().join(".tola/atomic.css")
        );
        let css = fs::read_to_string(second.path).unwrap();
        assert!(css.contains("Generated by Tola Atomic CSS"));
        assert!(css.contains(".grid"));
    }

    #[test]
    fn build_refuses_output_inside_configured_asset_source() {
        let temp = TempDir::new().unwrap();
        let root = temp.path();
        let content = root.join("content");
        fs::create_dir_all(&content).unwrap();
        fs::write(content.join("index.html"), r#"<div class="flex"></div>"#).unwrap();

        let mut config = SiteConfig::default();
        config.set_root(root);
        config.build.assets.nested = vec![crate::config::section::build::assets::NestedEntry::new(
            ".", "/",
        )];
        config.build.assets.normalize(root);
        config.build.output = root.to_path_buf();
        config.build.atomic_css.enable = true;

        let err = build(&config).unwrap_err();

        assert!(err.to_string().contains("inside configured asset source"));
        assert!(!root.join(".tola/atomic.css").exists());
    }

    #[test]
    fn build_refuses_to_overwrite_unowned_existing_output() {
        let temp = TempDir::new().unwrap();
        let root = temp.path();
        let content = root.join("content");
        let output = root.join("public");
        let output_css = output.join(".tola/atomic.css");
        fs::create_dir_all(&content).unwrap();
        fs::create_dir_all(output_css.parent().unwrap()).unwrap();
        fs::write(content.join("index.html"), r#"<div class="flex"></div>"#).unwrap();
        fs::write(&output_css, "user css").unwrap();

        let mut config = SiteConfig::default();
        config.set_root(root);
        config.build.output = output;
        config.build.atomic_css.enable = true;

        let err = build(&config).unwrap_err();

        assert!(err.to_string().contains("refusing to overwrite"));
        assert_eq!(fs::read_to_string(output_css).unwrap(), "user css");
    }
}
