// Tola SSG Typst library (v__VERSION__)
//
// Generated by `tola init`.
// Edit this file to customize your site's Typst helpers and templates.
//
// Provides:
// - page templates and HTML show rules
// - CSS class, path, content, date, and SEO helpers

// ============================================================================
// Math Rendering State
// ============================================================================

#let inside-figure = state("_tola-inside-figure", false)

// Inline math baseline fix (pin + measure).
#let bounded(eq) = text(top-edge: "bounds", bottom-edge: "bounds", eq)
#let equations-height-dict = state("eq_height_dict", (:))
#let is-inside-pin = state("inside_pin", false)

#let pin(label) = context {
  let height = here().position().y
  equations-height-dict.update(dict => {
    if label in dict.keys() or height < 0.000001pt {
      dict
    } else {
      dict.insert(label, height)
      dict
    }
  })
}

#let add-pin(eq) = {
  let label = repr(eq)
  is-inside-pin.update(true)
  $ inline(pin(label)#bounded(eq)) $
  is-inside-pin.update(false)
}

#let to-em(pt) = str(pt / text.size.pt()) + "em"

#let math-span(class: "", style: none, body) = {
  let attrs = (role: "math")
  if class != "" {
    attrs.insert("class", class)
  }
  if style != none {
    attrs.insert("style", style)
  }
  html.elem("span", body, attrs: attrs)
}

#let render-inline-math(eq, class: "") = context {
  if is-inside-pin.get() {
    return math-span(class: class)[#html.frame(bounded(eq))]
  }

  let label = repr(eq)
  let cache = equations-height-dict.final()
  if label in cache.keys() {
    let reference-height = cache.at(label, default: none)
    equations-height-dict.update(dict => {
      dict.insert(label, reference-height)
      dict
    })

    let measured-height = measure(bounded(eq)).height
    let shift = measured-height - reference-height
    let style = "vertical-align: -" + to-em(shift.pt()) + ";"
    math-span(class: class, style: style)[#html.frame(bounded(eq))]
  } else {
    math-span(class: class)[#box(html.frame(add-pin(eq)))]
  }
}

// ============================================================================
// HTML Show Rules
// ============================================================================

#let tola-base(
  // CSS classes for customization
  figure-class: "",
  math-inline-class: "",
  math-block-class: "",
  // Math font (string or array for fallback)
  math-font: "New Computer Modern Math",
  body,
) = {
  // Figure wrapper: use target() to avoid html.elem warnings inside html.frame()
  // internal paged render passes.
  show figure: it => context {
    if target() == "html" {
      inside-figure.update(true)
      let wrapped = html.figure(class: figure-class)[#it]
      inside-figure.update(false)
      wrapped
    } else { it }
  }

  // Note: No table show rule - Typst renders tables as native HTML <table>.
  // Using html.frame() on tables would convert them to SVG, causing internal
  // HTML elements (like html.code, html.span for math) to be ignored.

  show math.equation: set text(
    font: math-font,
    top-edge: "bounds",
    bottom-edge: "bounds",
  )

  // Math equations: use target()
  // - html.frame() internally renders to SVG using "paged" mode
  // - target() returns "paged" inside html.frame(), so the show rule skips
  show math.equation.where(block: false): it => context {
    if target() == "html" and not inside-figure.get() {
      render-inline-math(it, class: math-inline-class)
    } else { it }
  }

  show math.equation.where(block: true): it => context {
    if target() == "html" and not inside-figure.get() {
      html.div(class: math-block-class, role: "math")[#html.frame(it)]
    } else { it }
  }

  body
}

// ============================================================================
// Date Utilities
// ============================================================================

/// Parse a date string into a datetime object.
/// Only supports format: "YYYY-MM-DD" (e.g., "2024-01-15", "2024-1-5")
///
/// Example:
/// ```typst
/// parse-date("2024-01-15")  // => datetime(year: 2024, month: 1, day: 15)
/// parse-date("2024-1-5")    // => datetime(year: 2024, month: 1, day: 5)
/// parse-date(none)          // => none
/// ```
#let parse-date(s) = {
  if s == none { return none }
  if type(s) == datetime { return s }
  let s = str(s).split("T").at(0)
  let parts = s.split("-")
  assert(parts.len() == 3, message: "Invalid date format: '" + s + "', expected YYYY-MM-DD")
  datetime(year: int(parts.at(0)), month: int(parts.at(1)), day: int(parts.at(2)))
}

// ============================================================================
// Page Template
// ============================================================================

/// Page template with metadata for Tola SSG.
/// Usage: `tola-page(title: "...", ...)[body]` or `tola-page(title: "...", ..., head: [...])[body]`
///
/// Date fields (date, update) are automatically converted from string to datetime.
#let tola-page(
  // Content metadata (standard fields recognized by Tola SSG)
  title: none,
  summary: none,
  date: none,
  update: none,
  author: none,
  draft: false,
  tags: (),
  permalink: none,
  aliases: (),
  global-header: true,
  // Head content (optional)
  head: [],
  // Body content (required, positional)
  body,
  // Extra metadata fields (order, pinned, etc.)
  ..extra,
) = {
  // Auto-convert date strings to datetime
  let date = parse-date(date)
  let update = parse-date(update)

  [#metadata((
    title: title,
    summary: summary,
    date: date,
    update: update,
    author: author,
    draft: draft,
    tags: tags,
    permalink: permalink,
    aliases: aliases,
    global-header: global-header,
    ..extra.named(),
  )) <tola-meta>]

  show: tola-base

  // Keep this top-level branch outside context so query/validate sees body directly.
  let is-html = sys.inputs.at("format", default: "paged") == "html"
  if is-html {
    html.html[
      #html.head[#head]
      #html.body[#body]
    ]
  } else {
    body
  }
}

// ============================================================================
// Template Builder
// ============================================================================

/// Create a custom template with automatic parameter forwarding.
///
/// This helper reduces boilerplate when creating templates that extend tola-page.
/// It automatically handles:
/// - Parameter declaration and forwarding to tola-page
/// - Applying base show rules (won't forget `show: base`)
/// - Head content generation from metadata
///
/// Parameters:
/// - `base`: Show rule function to apply (e.g., your custom base with heading styles)
/// - `head`: Function `(meta) => content` to generate <head> content (e.g., og-tags)
/// - `view`: Function `(body, meta) => content` to wrap the body with layout
/// - `transform-meta`: Function `(meta) => meta` to transform metadata before passing to tola-page.
///   Use this to derive fields from source path (e.g., extract date/permalink from filename).
///
/// Example:
/// ```typst
/// #import "/tola/lib.typ": wrap-page, og-tags
/// #import "/templates/base.typ": base
///
/// #let post = wrap-page(
///   base: base,
///   head: (m) => og-tags(title: m.title, published: m.date),
///   view: (body, m) => {
///     show heading.where(level: 1): it => html.h2[#it.body]
///     html.article[
///       #if m.title != none { html.h1[#m.title] }
///       #body
///     ]
///   },
/// )
/// ```
#let wrap-page(
  base: none,
  head: none,
  view: (body, meta) => body,
  transform-meta: none,
) = (body, ..args) => {
  let meta = args.named()

  // Transform meta first (e.g., derive date/permalink from source)
  if transform-meta != none { meta = transform-meta(meta) }

  // Auto-convert date strings to datetime (after transform, so derived dates get converted)
  if "date" in meta { meta.date = parse-date(meta.date) }
  if "update" in meta { meta.update = parse-date(meta.update) }

  let head-content = if head == none { [] } else { head(meta) }
  let base-fn = if base == none { it => it } else { base }

  tola-page(..meta, head: head-content)[
    #show: base-fn
    #view(body, meta)
  ]
}

// ============================================================================
// CSS Class Utilities
// ============================================================================

/// Join CSS classes with automatic space handling.
/// Accepts strings, arrays, or none. Filters out empty/none values.
/// Normalizes multiple spaces to single space.
///
/// Example:
/// ```typst
/// cls("text-2xl", "font-bold")           // => "text-2xl font-bold"
/// cls("text-2xl font-bold", "mt-4")      // => "text-2xl font-bold mt-4"
/// cls("base", if active { "active" })    // => "base active" or "base"
/// cls("a", none, "b", "")                // => "a b"
/// cls(("a", "b"), "c")                   // => "a b c"
/// cls("a  b", "c")                       // => "a b c" (normalizes spaces)
/// ```
#let cls(..args) = {
  let flatten(items) = {
    let result = ()
    for item in items {
      if type(item) == array {
        result += flatten(item)
      } else {
        result.push(item)
      }
    }
    result
  }
  let raw = flatten(args.pos())
    .filter(x => x != none and x != "")
    .map(x => str(x))
    .join(" ")
  raw.split(" ").filter(x => x != "").join(" ")
}

/// Remove classes from a class string.
///
/// Example:
/// ```typst
/// cls-rm("a b c", "b")        // => "a c"
/// cls-rm("a b c", "b", "c")   // => "a"
/// cls-rm("a b c", ("a", "c")) // => "b"
/// cls-rm("a  b  c", "b")      // => "a c" (normalizes spaces)
/// ```
#let cls-rm(base, ..remove) = {
  let to-remove = cls(..remove).split(" ")
  cls(base).split(" ").filter(x => x not in to-remove).join(" ")
}

/// Toggle a class: add if missing, remove if present.
///
/// Example:
/// ```typst
/// cls-toggle("a b", "c")   // => "a b c"
/// cls-toggle("a b c", "b") // => "a c"
/// ```
#let cls-toggle(base, class) = {
  let classes = cls(base).split(" ")
  if class in classes {
    classes.filter(x => x != class).join(" ")
  } else {
    cls(base, class)
  }
}

/// Check if a class exists in a class string.
///
/// Example:
/// ```typst
/// cls-has("a b c", "b")   // => true
/// cls-has("a b c", "d")   // => false
/// cls-has("a  b  c", "b") // => true (handles extra spaces)
/// ```
#let cls-has(base, class) = {
  class in cls(base).split(" ")
}

// ============================================================================
// Path Utilities
// ============================================================================

/// Extract trailing number from the last path segment (for natural sorting).
/// Returns `none` if no trailing number found.
///
/// Example:
/// ```typst
/// trailing-num("/blog/post-1/")   // => 1
/// trailing-num("/blog/post-01/")  // => 1
/// trailing-num("/blog/post-1x2/") // => 2
/// trailing-num("/blog/post-10/")  // => 10
/// trailing-num("/blog/post-0/")   // => 0
/// trailing-num("/blog/intro/")    // => none
/// ```
#let trailing-num(s) = {
  let parts = s.split("/").filter(x => x != "")
  if parts.len() == 0 { return none }
  let chars = parts.last().clusters().rev()
  let digits = ()
  for c in chars {
    if c >= "0" and c <= "9" { digits.push(c) } else { break }
  }
  if digits.len() == 0 { none } else { int(digits.rev().join()) }
}

// ============================================================================
// Content Utilities
// ============================================================================

/// Convert content to plain string.
/// Recursively extracts text from content elements.
///
/// Example:
/// ```typst
/// to-string[Hello *world*]  // => "Hello world"
/// to-string(none)           // => ""
/// to-string(42)             // => "42"
/// ```
#let to-string(it) = {
  if it == none {
    ""
  } else if type(it) == str {
    it
  } else if type(it) != content {
    str(it)
  } else if it.has("text") {
    if type(it.text) == str {
      it.text
    } else {
      to-string(it.text)
    }
  } else if it.has("children") {
    it.children.map(to-string).join()
  } else if it.has("body") {
    to-string(it.body)
  } else if it == [ ] {
    " "
  } else {
    ""
  }
}

// ============================================================================
// HTML Utilities
// ============================================================================

/// Set the browser tab title via inline script.
///
/// Example:
/// ```typst
/// #import "@tola/site:0.0.0": info
/// #set-tab-title(page-title + " | " + info.author + "'s blog")
/// ```
#let set-tab-title(title) = {
  let s = title.replace("\\", "\\\\").replace("\"", "\\\"").replace("\n", "")
  html.script("document.title=\"" + s + "\";")
}

// ============================================================================
// SEO Utilities (Open Graph / Twitter Cards)
// ============================================================================

/// Generate a single OG meta tag.
/// - `prop`: property name (e.g., "og:title", "twitter:card")
/// - `content`: content value
#let _og-meta(prop, content) = {
  if content == none or content == "" { return none }
  let c = if type(content) == datetime {
    content.display("[year]-[month]-[day]")
  } else {
    to-string(content)
  }
  // OG/article/book/profile use "property" attribute, not supported by html.meta
  if (
    prop.starts-with("og:") or prop.starts-with("article:") or prop.starts-with("book:") or prop.starts-with("profile:")
  ) {
    html.elem("meta", attrs: (property: prop, content: c))
  } else {
    html.meta(name: prop, content: c)
  }
}

/// Generate Open Graph and Twitter Card meta tags.
///
/// All parameters are optional. Missing values will be omitted from output.
///
/// Supported og:type values:
/// - "website" (default for pages)
/// - "article" (default for posts)
/// - "book"
/// - "profile"
///
/// Parameters:
/// - `title`: Page title (og:title, twitter:title)
/// - `description`: Page description (og:description, twitter:description)
/// - `url`: Canonical URL (og:url)
/// - `image`: Preview image URL (og:image, twitter:image)
/// - `type`: Content type (og:type)
/// - `site-name`: Site name (og:site_name)
/// - `locale`: Locale string e.g. "en_US" (og:locale)
/// - Article-specific (type="article"):
///   - `author`: Author name or URL (article:author)
///   - `section`: Section/category (article:section)
///   - `published`: Published date ISO string (article:published_time)
///   - `modified`: Modified date ISO string (article:modified_time)
///   - `tags`: Array of tags (article:tag)
/// - Book-specific (type="book"):
///   - `author`: Author name or URL (book:author)
///   - `isbn`: ISBN number (book:isbn)
///   - `release-date`: Release date (book:release_date)
///   - `tags`: Array of tags (book:tag)
/// - Profile-specific (type="profile"):
///   - `first-name`: First name (profile:first_name)
///   - `last-name`: Last name (profile:last_name)
///   - `username`: Username (profile:username)
///   - `gender`: Gender (profile:gender)
/// - Twitter Card:
///   - `twitter-card`: Card type, default "summary_large_image"
///   - `twitter-site`: Twitter @username for the site
///   - `twitter-creator`: Twitter @username for the author
#let og-tags(
  title: none,
  description: none,
  url: none,
  image: none,
  type: "article",
  site-name: none,
  locale: none,
  // Article
  author: none,
  section: none,
  published: none,
  modified: none,
  tags: (),
  // Book
  isbn: none,
  release-date: none,
  // Profile
  first-name: none,
  last-name: none,
  username: none,
  gender: none,
  // Twitter
  twitter-card: "summary_large_image",
  twitter-site: none,
  twitter-creator: none,
) = context {
  if target() != "html" { return }

  // Open Graph basic
  _og-meta("og:title", title)
  _og-meta("og:description", description)
  _og-meta("og:url", url)
  _og-meta("og:image", image)
  _og-meta("og:type", type)
  _og-meta("og:site_name", site-name)
  _og-meta("og:locale", locale)

  // Type-specific metadata
  if type == "article" {
    _og-meta("article:author", author)
    _og-meta("article:section", section)
    _og-meta("article:published_time", published)
    _og-meta("article:modified_time", modified)
    for tag in tags { _og-meta("article:tag", tag) }
  } else if type == "book" {
    _og-meta("book:author", author)
    _og-meta("book:isbn", isbn)
    _og-meta("book:release_date", release-date)
    for tag in tags { _og-meta("book:tag", tag) }
  } else if type == "profile" {
    _og-meta("profile:first_name", first-name)
    _og-meta("profile:last_name", last-name)
    _og-meta("profile:username", username)
    _og-meta("profile:gender", gender)
  }
  // "website" has no additional properties

  // Twitter Cards
  _og-meta("twitter:card", twitter-card)
  _og-meta("twitter:title", title)
  _og-meta("twitter:description", description)
  _og-meta("twitter:image", image)
  _og-meta("twitter:site", twitter-site)
  _og-meta("twitter:creator", twitter-creator)
}
