//! One pronunciation table: the names it carries and the lookup over them.

use std::io::Read as _;
use std::sync::LazyLock;

/// The run slots a table's leading byte pairs index: one slot per pair of bytes, and one
/// past the last pair for the end of the table.
///
/// A table trades 256 KiB of slots for it — held for the process, like its entries — so a
/// lookup starts in the run of names carrying the text's leading pair instead of the run
/// carrying its first byte alone, and partitions a shorter slice.
const RUN_SLOTS: usize = (1 << 16) + 1;

/// One source's table of names and their pronunciations, parsed by the first lookup.
pub(crate) type PronunciationTable = LazyLock<Names>;

/// One line of a generated table: where its name and its pronunciation sit in the
/// table's bytes.
struct Entry {
    /// The offset of the name's first byte.
    start: u32,
    /// How many bytes the name takes.
    name_bytes: u16,
    /// How many bytes the pronunciation after the tab takes.
    pronunciation_bytes: u16,
}

/// The names one generated table carries.
pub(crate) struct Names {
    /// The generated bytes every entry slices.
    generated: String,
    /// The entries, ordered by the name's bytes.
    entries: Vec<Entry>,
    /// Where the run of names carrying each leading pair begins.
    runs: Box<[u32; RUN_SLOTS]>,
}

/// The pair of leading bytes a name or a text is indexed under, read big-endian; a byte
/// string of one byte reads as that byte and a zero second byte.
fn leading_pair(bytes: &[u8]) -> Option<usize> {
    let first = *bytes.first()?;
    Some(((first as usize) << 8) | bytes.get(1).copied().unwrap_or(0) as usize)
}

/// Decode the frame the generator wrote for one table.
///
/// The stream is this crate's own generated table, so decoding it needs no bound.
#[cfg(any(feature = "cedict", feature = "jmdict", feature = "unihan"))]
pub(crate) fn decompress(compressed: &[u8]) -> Vec<u8> {
    let mut generated = Vec::new();
    ruzstd::decoding::StreamingDecoder::new(compressed)
        .expect("a table's bytes are the frame the generator wrote")
        .read_to_end(&mut generated)
        .expect("a table's bytes decode");
    // The table lives for the process, so the growth slack is not kept.
    generated.shrink_to_fit();
    generated
}

impl Names {
    /// Parse a generated table: `#` comments, then `name<TAB>pronunciation` lines.
    #[cfg_attr(
        not(any(feature = "cedict", feature = "jmdict", feature = "unihan")),
        allow(
            dead_code,
            reason = "with no source enabled there is no table to parse"
        )
    )]
    pub(crate) fn parse(generated: Vec<u8>) -> Self {
        let text = String::from_utf8(generated).expect("a generated table is UTF-8");
        // An entry addresses the table with 32-bit offsets.
        u32::try_from(text.len()).expect("a generated table fits in the index's offsets");
        let base = text.as_ptr() as usize;
        let mut entries = Vec::new();
        // A lookup starts in the run of names carrying the text's leading bytes, so the runs
        // are read off the ordered lines in the same pass that reads the entries.
        let mut runs: Box<[u32; RUN_SLOTS]> = vec![0; RUN_SLOTS]
            .try_into()
            .expect("a table indexes one slot per pair of leading bytes");
        let mut run = 0;
        let mut previous_name = None;
        for line in text.lines() {
            if line.is_empty() || line.starts_with('#') {
                continue;
            }
            let (name, pronunciation) = line
                .split_once('\t')
                .expect("a generated table names a pronunciation after a tab");
            // The lookup compares names and narrows runs of them, so the table the
            // generator writes is ordered by the bytes those comparisons use.
            if let Some(previous) = previous_name {
                assert!(
                    previous <= name,
                    "a generated table is ordered by the name's bytes"
                );
            }
            previous_name = Some(name);
            let head = leading_pair(name.as_bytes())
                .expect("a generated table holds a name for every pronunciation");
            while run <= head {
                runs[run] = entries.len() as u32;
                run += 1;
            }
            entries.push(Entry {
                start: (line.as_ptr() as usize - base) as u32,
                name_bytes: u16::try_from(name.len())
                    .expect("a generated table's name fits in an entry"),
                pronunciation_bytes: u16::try_from(pronunciation.len())
                    .expect("a generated table's pronunciation fits in an entry"),
            });
        }
        while run < RUN_SLOTS {
            runs[run] = entries.len() as u32;
            run += 1;
        }
        Self {
            generated: text,
            entries,
            runs,
        }
    }

    /// The name one entry carries.
    fn name(&self, entry: &Entry) -> &str {
        let start = entry.start as usize;
        &self.generated[start..start + entry.name_bytes as usize]
    }

    /// The pronunciation one entry carries.
    fn pronunciation(&self, entry: &Entry) -> &str {
        // The name is followed by the tab that parts it from its pronunciation.
        let start = entry.start as usize + entry.name_bytes as usize + 1;
        &self.generated[start..start + entry.pronunciation_bytes as usize]
    }

    /// The entries a lookup for `text` starts in.
    ///
    /// A name that can match carries the text's first character, so the pair its leading
    /// bytes spell names the run to start in.
    fn run_of(&self, text: &str) -> &[Entry] {
        let bytes = text.as_bytes();
        let Some(&first) = bytes.first() else {
            return &[];
        };
        let (first_pair, last_pair) = if first < 0x80 {
            // A one-byte first character carries no second byte to narrow with, and every
            // pair starting with its byte leads to the names that can match.
            let first = (first as usize) << 8;
            (first, first | 0xFF)
        } else {
            let pair = leading_pair(bytes).expect("a non-empty byte string has a leading pair");
            (pair, pair)
        };
        &self.entries[self.runs[first_pair] as usize..self.runs[last_pair + 1] as usize]
    }

    /// The longest name `text` starts with, and the pronunciation it carries.
    ///
    /// Entries are ordered by the name's bytes, so the names that carry one prefix are a
    /// single run of them. The text's leading bytes name the run to start in, and each
    /// character narrows the run its predecessor left; the run is empty as soon as no name
    /// carries the prefix, and a name equal to the prefix is a run's first entry, because a
    /// name sorts before every longer name that carries it.
    fn longest_match(&self, text: &str) -> Option<(&str, &str)> {
        let mut candidates = self.run_of(text);
        if candidates.is_empty() {
            return None;
        }
        let mut longest = None;
        for (offset, character) in text.char_indices() {
            let prefix = &text[..offset + character.len_utf8()];
            let run = candidates.partition_point(|entry| self.name(entry) < prefix);
            let Some(first) = candidates.get(run) else {
                break;
            };
            let name = self.name(first);
            // The names carrying the prefix are one run of the ordered entries, so the
            // first entry past the shorter names carries it unless no name does.
            if !name.starts_with(prefix) {
                break;
            }
            if name.len() == prefix.len() {
                longest = Some((name, self.pronunciation(first)));
            }
            candidates = &candidates[run..];
            candidates = &candidates
                [..candidates.partition_point(|entry| self.name(entry).starts_with(prefix))];
        }
        longest
    }
}

/// Replace every name `text` carries with its pronunciation, and report whether any was.
///
/// A pronunciation is a word, so it is kept apart from the text around it: it is preceded
/// by a space, and one follows it before a letter or number. A character that would draw
/// together with the pronunciation's last character without being a letter or number — a
/// combining mark — is copied as it is, so a caller that folds its result must keep that
/// mark from joining the pronunciation. Text no source names is copied as it is: the
/// caller decides what its own characters mean.
pub(crate) fn rewrite(sources: &[&PronunciationTable], text: &str) -> Option<String> {
    if sources.is_empty() {
        return None;
    }
    let mut rewritten = None;
    let mut rest = text;
    let mut after_pronunciation = false;
    while let Some(character) = rest.chars().next() {
        // The longest name wins; a tie keeps the source that comes first.
        let mut found = None;
        for source in sources {
            let Some(candidate) = source.longest_match(rest) else {
                continue;
            };
            // Two names matching one position are prefixes of that text and so of each
            // other, which makes the longer name the one with more bytes.
            let longer = found.is_none_or(|(name, _): (&str, &str)| candidate.0.len() > name.len());
            if longer {
                found = Some(candidate);
            }
        }
        match found {
            Some((name, pronunciation)) => {
                let rewritten = rewritten.get_or_insert_with(|| {
                    let mut prefix = String::with_capacity(text.len());
                    prefix.push_str(&text[..text.len() - rest.len()]);
                    prefix
                });
                if !rewritten.is_empty() && !rewritten.ends_with(' ') {
                    rewritten.push(' ');
                }
                rewritten.push_str(pronunciation);
                after_pronunciation = true;
                rest = &rest[name.len()..];
            }
            None => {
                let length = character.len_utf8();
                if let Some(rewritten) = &mut rewritten {
                    if after_pronunciation
                        && character.is_alphanumeric()
                        && !rewritten.ends_with(' ')
                    {
                        rewritten.push(' ');
                    }
                    rewritten.push_str(&rest[..length]);
                }
                after_pronunciation = false;
                rest = &rest[length..];
            }
        }
    }
    rewritten
}

#[cfg(test)]
mod tests {
    use super::{Names, PronunciationTable, rewrite};

    static ASCII_TABLE: PronunciationTable = PronunciationTable::new(|| {
        Names::parse(b"# names and their pronunciations\nab\tx\nabc\ty\nc\tz\n".to_vec())
    });

    #[test]
    fn longest_name_wins() {
        assert_eq!(rewrite(&[&ASCII_TABLE], "abc"), Some("y".into()));
    }

    #[test]
    fn pronunciations_keep_word_boundaries() {
        for (text, pronunciations) in [
            ("ab c", "x z"),
            ("é界xabcδ", "é界x y δ"),
            ("xab c", "x x z"),
            ("ab-c", "x- z"),
            ("ab, c", "x, z"),
        ] {
            assert_eq!(
                rewrite(&[&ASCII_TABLE], text).as_deref(),
                Some(pronunciations)
            );
        }
    }

    #[test]
    fn unknown_text_stays_unmatched() {
        for text in ["zzz", "11", "é界", ""] {
            assert_eq!(rewrite(&[&ASCII_TABLE], text), None);
        }
    }

    #[test]
    fn empty_sources_leave_text_unchanged() {
        assert_eq!(rewrite(&[], "abc東京"), None);
    }

    #[test]
    fn longer_name_beats_source_precedence() {
        static PREFIX_TABLE: PronunciationTable =
            PronunciationTable::new(|| Names::parse(b"ab\tprefix\n".to_vec()));
        assert_eq!(
            rewrite(&[&PREFIX_TABLE, &ASCII_TABLE], "abc"),
            Some("y".into())
        );
    }

    #[test]
    fn earlier_source_wins_tie() {
        static FIRST: PronunciationTable =
            PronunciationTable::new(|| Names::parse(b"abc\tfirst\n".to_vec()));
        static SECOND: PronunciationTable =
            PronunciationTable::new(|| Names::parse(b"abc\tsecond\n".to_vec()));
        assert_eq!(rewrite(&[&FIRST, &SECOND], "abc"), Some("first".into()));
        assert_eq!(rewrite(&[&SECOND, &FIRST], "abc"), Some("second".into()));
    }

    #[test]
    fn shared_leading_bytes_resolve_each_name() {
        // 一 and 中 carry the same leading pair; 一心 carries it and continues past 一.
        static PAIR_TABLE: PronunciationTable = PronunciationTable::new(|| {
            Names::parse("一\tyi\n一心\tone heart\n中\tzhong\n".as_bytes().to_vec())
        });
        // 中 and 乀 share only their first byte; 乀 opens the pair that follows 中's.
        static NEIGHBOURS_TABLE: PronunciationTable =
            PronunciationTable::new(|| Names::parse("中\tzhong\n乀\tfu\n".as_bytes().to_vec()));
        // A one-byte first character carries no second byte to narrow with, so a lookup for
        // `3x` still meets the names opening with `3`.
        static ONE_BYTE_TABLE: PronunciationTable = PronunciationTable::new(|| {
            Names::parse("3\tthree\n3D\tthree de\n".as_bytes().to_vec())
        });

        for (table, cases) in [
            (
                &PAIR_TABLE,
                &[("中", "zhong"), ("一", "yi"), ("一心", "one heart")][..],
            ),
            (&NEIGHBOURS_TABLE, &[("乀", "fu"), ("中", "zhong")][..]),
            (
                &ONE_BYTE_TABLE,
                &[("3x", "three x"), ("3D", "three de")][..],
            ),
        ] {
            for &(text, expected) in cases {
                assert_eq!(rewrite(&[table], text).as_deref(), Some(expected), "{text}");
            }
        }
    }
}
